### ISSUE TITLE
Would love a feature to re run a task on file change

### ISSUE THREAD

**Issue by chasinglogic** [go-task/task#1]
If I could have this re run a task whenever a file changes in the source directory that would be a huge boon, I'd be willing to help contribute to this feature.

**Comment by andreynering** [comment]
I think feature would be a good adition.

We could have a `-w` (watch) flag for it. Also, we could use the current `sources` attribute.

I'd be happy to review a PR for that.

**Comment by alioygur** [comment]
+1

I think it would be great.

**Comment by Pezhin** [comment]
Are you willing to use any new package to do the "watch" things?

**Comment by andreynering** [comment]
@Pezhin Yeah, I think I'll be necessary to use an external lib.

**Comment by sascha-andres** [comment]
Maybe it is possible to use https://github.com/yosssi/goat

**Comment by andreynering** [comment]
I think this is what we need:

https://github.com/fsnotify/fsnotify

**Comment by andreynering** [comment]
A first interation on watching a task is available on [watch branch][watch]. Just inform `sources` for a task and give `--watch` or `-w` flag.

Tests and feedback are welcome.

[watch]: https://github.com/go-task/task/tree/watch

**Comment by sascha-andres** [comment]
@andreynering will test at work

**Comment by andreynering** [comment]
Implemented as an experimental feature on master branch.
