### ISSUE TITLE
Add `splitArgs` template function to allow to reliably get arguments of `CLI_ARGS`

### ISSUE THREAD

**Issue by andreynering** [go-task/task#1040]
Idea came from: https://github.com/go-task/task/issues/327#issuecomment-1458388507

We should use the shell parser library to do that (`mvdan/sh`).

Reminder: [Update documentation](https://taskfile.dev/usage/#forwarding-cli-arguments-to-commands) to mention this possibility.

**Comment by dhanusaputra** [comment]
hi, may I help with this task? thanks

**Comment by gabyx** [comment]
This feature should be provided by Task itself in the form of `.CLI_ARGUMENTS` which is passed as `[]string`.
It makes absolutely no sense to go over templating to then reextract the arguments.

**Comment by mpyw** [comment]
I agree with that. The actual feature we've wanted is receiving variables through `"$@"`.
