### ISSUE TITLE
Documentation: Add a "template funcs" section to the API reference page

### ISSUE THREAD

**Issue by andreynering** [go-task/task#1041]
I just realized the [API reference page](https://taskfile.dev/api/) missed a section mentioning all the additional functions we implement on top of [slim-sprig](https://github.com/go-task/slim-sprig).

We should have a paragraph before the table linking to the slim-sprig documentation: https://go-task.github.io/slim-sprig/.

https://github.com/go-task/task/blob/a29e5d39ca804ec6289cc21a67be372dd7a17b6f/internal/templater/funcs.go#L18-L46

**Comment by ayushmaanshrotriya** [comment]
will do

**Comment by ayushmaanshrotriya** [comment]
you can assign me this issue

**Comment by vmaerten** [comment]
This has been done : https://github.com/go-task/task/pull/1653
