### ISSUE TITLE
Proposal: Migrate `master` to `main`

### ISSUE THREAD

**Issue by pd93** [go-task/task#1049]
This issue proposes and tracks the changes required to rename Task's `master` branch to Git's new default branch name: `main`.  
GitHub has a repo that has [guidance for changing the default branch from `master`](https://github.com/github/renaming) that informs the rest of this issue.

The steps required to do this are pretty simple:

- [ ] Rename `master` to `main`
  - Note that (among other things) this will automatically:
    - Re-target any open pull requests
    - Move any branch protection rules that explicitly reference the old name
    - Redirect web requests for the old branch name to the new branch name
  - [See docs](https://github.com/github/renaming#renaming-existing-branches) for instructions and more info.
- [ ] Merge #1048
  - Most of these changes aren't strictly necessary thanks to GitHub's automatic redirection. However, it nice to have everything up to date :)

## A note to maintainers of [community projects](https://taskfile.dev/community/)

Very few of the community-made Task projects directly refer to Task's `master` branch and since GitHub will automatically redirect requests from `master` to `main`, there shouldn't be any issues with breaking 3rd party integrations. However, if you do maintain a project that refers to Task's `master` branch, it's probably a good idea to update any references to `main` if this issue is completed.

The only project I'm aware of that currently refers to `master` is the [Homebrew formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/go-task.rb#L7).

**Comment by andreynering** [comment]
Opened https://github.com/Homebrew/homebrew-core/pull/128481 to reflect this change on Homebrew.
