### ISSUE TITLE
Help site supports multiple languages.

### ISSUE THREAD

**Issue by misitebao** [go-task/task#1057]
I would like to contribute to document translation.

First of all, I checked https://github.com/go-task/task/issues/921, and I have some understanding of the current document translation situation. I am more in favor of the first solution mentioned by @andreynering, which will be more The language documentation is concentrated on one site, which is also the solution used by most sites that use [Docusaurus](https://docusaurus.io/). Coincidentally, I am familiar with Docusaurus and can help complete the multilingual setup.

The next step is the specific translation steps. The project maintainers only need to maintain the most basic English documents. The translation of other languages can be handed over to the community. There are many ways to translate:
   1. Translators translate and submit PRs themselves, and maintainers review and merge them.
   2. Use an online localization translation platform. I personally recommend [Crowdin](https://crowdin.com/). [I am currently using it](https://crowdin.com/project/wails). Using it, multiple people can process translation work online, and you can also check the translation progress and approval progress in real time. All the maintenance personnel need to do is Get translated files from Crowdin regularly, and of course they also provide a full toolchain for that matter.

The above are my personal suggestions, if adopted, I am more than willing to help.

By the way, I am currently translating Chinese documents, and the progress is about 80%. I also checked the existing Chinese document mentioned in the document, but I found that it has not been updated for a long time, and it is not synchronized with the current English document.

**Comment by misitebao** [comment]
Hi, @andreynering @DeronW
Crowdin works well with Docusaurus and I already have a complete workflow to use for this project.

However, based on my experience, I personally don't agree with using Crowdin's automated integration tool because it has a slight problem, so I prefer to do it manually.

If one agrees to use Crowdin, I can help with all the setup.

**Comment by DeronW** [comment]
I'm not familiar with Crowdin, but I think it's a good idea, and it's happy to see new version of Chinese doc

**Comment by DeronW** [comment]
> 

I'm not familiar with Crowdin, but I think it's a good idea, and it's happy to see new version of Chinese doc

> Hi, @andreynering @DeronW Crowdin works well with Docusaurus and I already have a complete workflow to use for this project.
> 
> However, based on my experience, I personally don't agree with using Crowdin's automated integration tool because it has a slight problem, so I prefer to do it manually.
> 
> If one agrees to use Crowdin, I can help with all the setup.

I'm not familiar with Crowdin, but I think it's a good idea, and it's happy to see new version of Chinese doc
