### ISSUE TITLE
Versions 2.* are not distinguishable 

### ISSUE THREAD

**Issue by EmilySeville7cfg** [go-task/task#1078]
Documentation [lists](https://taskfile.dev/taskfile-versions/#version-20) changes made in 2.* versions, but `version` key in code examples is still `2` everywhere. Is it a mistake? I need to know to update schema.

- Task version:
- Operating System:

**Comment by richard-hajek** [comment]
As far as I can tell the code base fully supports any semver so "2.6" for example should work too, haven't tested it though

**Comment by richard-hajek** [comment]
I am 99% sure it's a mistake in the doc, although technically, all the taskfiles are valid, because `version: "2"  `really means "version 2.0.0 or higher but lower than 3.0.0"

**Comment by pd93** [comment]
Closing this issue now.

Also worth mentioning that v2 schemas are now deprecated #1197
