### ISSUE TITLE
A few small issues with npm package @go-task/cli

### ISSUE THREAD

**Issue by kenbankspeng** [go-task/task#1081]
Fantastic task runner.

Not the end of the world, but a few small issues with npm package @go-task/cli.

1 - unable to remove npm package @go-task/cli using npm.

Reproduce:
- `npm -g install @go-task/cli` --> correctly adds @go-task/cli to list of global packages and places task binary in node's bin directory as a global npm package 
- `npm -g remove @go-task/cli` --> correctly removes @go-task/cli from list of global places but erroneously does not delete the task binary from node's bin directory. 

2 - task always installs globally (but maybe is inherent since task is a bin and not javascript code and need to piggyback on existing node $PATH)

Reproduce:
- `npm -g install @go-task/cli` --> correctly installs task globally
- `npm --save-dev install @go-task/cli` --> erroneously installs task globally instead of within local node_modules folder

**Comment by kenbankspeng** [comment]
I correctly observe under `/usr/local/node_modules/@go-task/cli/packages.json` that you have specified `"preuninstall": "go-npm uninstall"`.

So seems this might be an issue with go-npm.

**Comment by dvgitit** [comment]
On npmjs.com there is still only version 3.21.0 available. 3.22.0 is not available yet.

**Comment by andreynering** [comment]
The missing v3.22.0 release mentioned by @dvgitit is fixed. I just pushed v3.23.0 as well.
