### ISSUE TITLE
Move the `npm package` file to `/npm/@go-task/cli` directory

### ISSUE THREAD

**Issue by misitebao** [go-task/task#1119]
Request to move the `npm package` file to the corresponding subdirectory to keep the root directory clean.

**Comment by andreynering** [comment]
I believe we're talking about only 2 files here: `package.json` and `package-lock.json`. I'm not sure this is worth it. Do these 2 files cause any harm on the root dir?

**Comment by misitebao** [comment]
Just want to make the root directory a little tidier, and make the project not look like a `Nodejs` project at first glance.😂
