### ISSUE TITLE
export PATH=$PWD:$PATH

### ISSUE THREAD

**Issue by gedw99** [go-task/task#1127]
export PATH=$PWD:$PATH

does not work when used like below, but works on command before i run task.

```
cmds:
      - export PATH=$PWD:$PATH

```

**Comment by pd93** [comment]
Each command runs in its own shell and so variables are not persisted between them. There are some alternative approaches discussed in #1115. We're also working on improving our docs to address this as its a very commonly asked question.

**Comment by gedw99** [comment]
thanks
