### ISSUE TITLE
Allow single command/cmd under task

### ISSUE THREAD

**Issue by timdp** [go-task/task#1130]
I can't imagine this hasn't been discussed before but maybe I suck at using search. Anyway:

Personally, I try to keep my Taskfiles really succinct. As soon as a command/script becomes a little involved, I'll quickly fork out to a dedicated script file (sacrificing Go sh support). That means that my tasks are usually one-liners.

Now, when only specifying the command itself, I can use the shorthand task declaration format, which is really intuitive:

```yaml
tasks:
  foo: scripts/foo.sh
```

However, when the task require more configuration—e.g., `deps`, `desc`, `vars`—, that forces me to specify the same command as a single-item array, adding a bit of overhead:

```yaml
foo:
  deps: [bar, baz]
  cmds:
    - scripts/foo.sh
```

I suppose I could collapse the second array too, but it will quickly become a kludge:

```yaml
foo:
  deps: [bar, baz]
  cmds: ['[[ -f file ]] && scripts/foo.sh {{.CLI_ARGS}}']
```

So I was wondering if it wouldn't make sense to also accept a string instead of an array of strings—either as the existing `cmds` or under a new `cmd` key at the task level:

```yaml
foo:
  deps: [bar, baz]
  cmd: scripts/foo.sh
```

This shouldn't be confused with `cmd` _inside_ items in the `cmds` array. However, it serves the same purpose, and therefore, I think it makes sense to allow it one level higher as well.

While I'm personally also not a huge fan of these situations where configuration items are mutually exclusive, I think this particular feature would really allow us to write cleaner and less verbose Taskfiles.

Looking forward to hearing your thoughts. Thanks in advance.

**Comment by timdp** [comment]
Turns out this is actually [documented](https://github.com/go-task/task/blob/c2523796c0de468c25b19f49ca257fe43ea470e2/docs/docs/api_reference.md?plain=1#L243-L244) as implemented already, but with v3.24.0, the following doesn't `echo Foo` for me:

```
version: "3"

tasks:  foo:
    deps: [bar]
    cmd: echo Foo

  bar: echo Bar
```

**Comment by andreynering** [comment]
Any opinion on this @pd93? I think it makes sense for me but a second opinion could be interesting.

The alternative would be to allow a string on `cmds: echo hello`. The advantage is that it wouldn't need a second key, but on the other side the name in plural would look weird.

@timdp A couple of comments on your code on #1131:

- A think we need to return an error if both `cmd:` and `cmds:` are returned.
- We need to update the [schema.json](https://github.com/go-task/task/blob/main/docs/static/schema.json) file to reflect this change.

**Comment by pd93** [comment]
@andreynering Sorry, I missed this notification somehow. I think this makes a lot of sense to have. My only concern is that we already have quite a few ways of writing a command:

Standard:
```yml
foo:
  cmds:
    - echo "foo"
```
Short:
```yml
foo: echo "foo"
```
Detailed command:
```yml
foo:
  cmds:
    - cmd: echo "foo"
      silent: true
```

This is going to add a fourth (let's call it "detailed task"):

```yml
foo:
  cmd: echo "foo"
  silent: true
```

We should consider updating the documentation to be super clear about the different methods and why/when you would use them. Otherwise I think this is going to create a lot of confusion. The names I used to distinguish them above are probably awful and would require a bit more thought.

> The alternative would be to allow a string on `cmds: echo hello`. The advantage is that it wouldn't need a second key, but on the other side the name in plural would look weird.

I would lean towards having `cmd` instead. This is then consistent with `cmd` being a string on the "detailed command" example above.
