### ISSUE TITLE
Latest refactor of task/cmd/task/task.go is swallowing errors

### ISSUE THREAD

**Issue by clintmod** [go-task/task#1133]
> Thanks for your bug report!
>
> Before submitting this issue, please make sure the same problem was
> not already reported by someone else.
>
> Please describe the bug you're facing. Consider pasting example
> Taskfiles showing how to reproduce the problem.

- Task version: 3.24.0
- Operating System: MacOS Monterey 12.6

Here's the code:

https://github.com/go-task/task/blob/c2523796c0de468c25b19f49ca257fe43ea470e2/cmd/task/task.go#L46-L54

just need a `log.Fatal(err)` before line 52

I'll send a PR

**Comment by pd93** [comment]
@clintmod Thanks for the report! Left a very minor comment on your PR

**Comment by krystian-panek-wttech** [comment]
is it the same what I just observed?

![image](https://user-images.githubusercontent.com/81212505/234521667-ea451b88-8c46-4cf4-ad3a-5177196946cb.png)

after upgrading from 3.20.0 => 3.24.0 I see doubled `task: Failed` lines... 
after downgrading there is again single line...
