### ISSUE TITLE
Environment variables not expanded within task directory

### ISSUE THREAD

**Issue by ilikebits** [go-task/task#116]
I want to run a task in `$GOPATH/github.com/some/project`, but this causes `task: Failed to run task "taskname": chdir $GOPATH/github.com/some/project: no such file or directory` even though the folder exists. Hardcoding the value of `$GOPATH` works around this issue.

**Comment by andreynering** [comment]
Hi @ilikebits!

Thanks for reporting. This is now fixed on master branch. Let me know if you still have issues.
