### ISSUE TITLE
Package on conda-forge for conda/mamba

### ISSUE THREAD

**Issue by AntoinePrv** [go-task/task#1172]
Hello,

 I am packaging go-task on Conda-Forge, a community-led, cross-platform, cross-language, repository for the conda/mamba package manager.
 Would any of the maintainer be interested to join in maintaining the recipe?
 https://github.com/conda-forge/staged-recipes/pull/22844

**Comment by andreynering** [comment]
Hi @AntoinePrv,

Thanks for letting us know!

We already have limited time to work on Task itself, and we also don't have any previous experience with this package manager, so it'd be better if the community maintained it.

We already have other packages maintained by the community, [as mentioned in the documentation](https://taskfile.dev/community/#installation-methods). We wouldn't be able to maintain so many ourselves.

I hope you understand.

**Comment by andreynering** [comment]
Forgot to say that, if you want to see this one listed on [the community page](https://taskfile.dev/community/#installation-methods), just open a PR. 🙂
