### ISSUE TITLE
cmds do not support `$!` 

### ISSUE THREAD

**Issue by paulo-raca** [go-task/task#1189]
Hello,

One of my task needs to start a background, and later kill it.

In order to kill it later, I need to retrieve the PID of the background server, which I usually do with `$!` in a shell.

However it looks like this variable doesn't work inside Taskfiles (everything else does).

Here is a minimal reproduction:

```yaml
version: "3"

tasks:
  x:
    cmds:
      - |
        sleep 1&
        echo PID=$!
```

```sh
$ task -s x
PID=
```

The same script works when executed by bash or sh:

```sh
$ sh test.sh 
PID=2400946
```

---

For context, my real use case is to start an HTTP server, execute some commands that require it, then shutting down the server. the actual script looks like this:

```sh
#!/bin/bash

# Executes e2e tests from a local webserver
# This sounds easy enough in theory, but starting the server in background, waiting
# until it is ready and finally shuting it down when done is somewhat cumbersome.

export PORT=1234
2>>/dev/null >>/dev/tcp/localhost/$PORT && { echo "localhost:$PORT is in use" && exit 1; }

echo Starting server
# For whatever reason "yarn run serve" doesn't stop with "kill $server_pid", so this uses node directly
node node_modules/.bin/docusaurus serve --port=$PORT --no-open &
server_pid=`echo $!`

trap 'kill $server_pid && wait $server_pid' EXIT

timeout 10 bash -c 'until 2>>/dev/null >>/dev/tcp/localhost/$PORT; do sleep 1; done' || { echo "server didn't start" && exit 1; }

echo server ready, starting test
SERVER_BASE_URL="http://localhost:$PORT" yarn test:e2e
```

---

- Task version: v3.25.0 (h1:XtIEtWpQSbIf2FGU+44/QB1whFf2sBUB/02W7ZQSz0U=)

- Operating System: Kubuntu Linux 22.10

**Comment by andreynering** [comment]
Hi @paulo-raca,

This may never happen due to limitations given we're using an interpreter written in Go.

I'm closing this because there's an upstream issue about it, and interactions about this feature should happen there:

https://github.com/mvdan/sh/issues/221
