### ISSUE TITLE
Help setting version in Arch Linux package

### ISSUE THREAD

**Issue by carlsmedstad** [go-task/task#1207]
I'm struggling to have the binary output the correct version for the AUR package.

See the the `build` function in the [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=go-task):

```sh
build() {
  cd "$_archive"

  export CGO_CPPFLAGS="${CPPFLAGS}"
  export CGO_CFLAGS="${CFLAGS}"
  export CGO_CXXFLAGS="${CXXFLAGS}"
  export CGO_LDFLAGS="${LDFLAGS}"
  export GOFLAGS="-buildmode=pie -trimpath -ldflags=-linkmode=external -mod=readonly -modcacherw"

  go build -v -o bin ./cmd/task
}
````

I've tried setting multiple ld flags but I've been unable to get any other output than:

```sh
$ go-task --version
Task version: (devel)
```

For example `-X github.com/go-task/task/version=$pkgver` which I found here: https://github.com/go-task/task/issues/1050.

Assistance very much appreciated.

**Comment by andreynering** [comment]
Hi @carlsmedstad,

This is the flag you need to add to `go build` or `go install`:

```bash
-ldflags="-X github.com/go-task/task/v3/internal/version.version=v9.9.9"
```

Let me know if that works for you or not.

**Comment by carlsmedstad** [comment]
Works like a charm, thank you @andreynering!
