### ISSUE TITLE
Taskfile taking a few seconds before executing command

### ISSUE THREAD

**Issue by lockieluke** [go-task/task#1235]
- Task version: v3.26.0
- Operating system: macOS Sonoma with Xcode 15 Beta 2
- Experiments enabled: None

Any command you execute with Task would trigger `xcodebuild` and show the xcodebuild messages and wait for a few seconds before executing the underlying commands
![image](https://github.com/go-task/task/assets/25424409/3b3e57e1-43b1-482c-91da-268062206a30)

**Comment by andreynering** [comment]
Hi @lockieluke,

How did you installed Task in your system?

Does this only happen with this Taskfile? What happens when you run an empty one like?:

```yaml
version: '3'

tasks:
  echo:
    cmds:
      - echo 'testing'
```

**Comment by lockieluke** [comment]
apparently it's xcodebuild that is taking up that few seconds
