### ISSUE TITLE
Dry Run Ability

### ISSUE THREAD

**Issue by bobhenkel** [go-task/task#125]
- Task version - Task version: 2.0.2
- OS - OSX and Linux

Awesome app!  Is there anyway to have the ability to do a dry run.  For example say I have a tast called build_and_publish

```
task --dry-run build_and_publish
```
By adding dry run all my task place holders would be filled in and I could print out the commands that would be executed if I removed --dry-run. This would help debug a task file.

Thanks
Bob

**Comment by andreynering** [comment]
Hi @bobhenkel,

Thanks for the suggestion

I think this feature request makes sense, and should be relatively easy to implement

**Comment by andreynering** [comment]
Implemented on #126 

See https://github.com/go-task/task#dry-run-mode
