### ISSUE TITLE
Special variables to provide platform, system architecture

### ISSUE THREAD

**Issue by shakfu** [go-task/task#1265]
It would be very useful to have have a special variable which provide standard consistent info about the runtime platform: for example Darwin, Windows, Linux .... also  another to give architecture: x86_53, arm64, etc..

This is especially helpful if one want to conditional change a part of a dynamic variable depending up one of the above. For 'a' for Darwin or Linux and '.lib' fo Windows.

The only way I know how to do this is to inject the information from an environment variable.

**Comment by andreynering** [comment]
Hi @shakfu,

There's `{{OS}}` and `{{ARCH}}`. See: https://taskfile.dev/usage/#gos-template-engine

Note that they are _functions_ and not _variables_, which means you need to omit the dot (`.`) for them.

**Comment by shakfu** [comment]
Hi @andreynering 

That's great to know and now it makes much better sense. 

Thanks very much for the quick clarification. I think I went  straight to the API section and somehow missed that part of the the usage section. :innocent:
