### ISSUE TITLE
--exit-code doesn't work for nested tasks

### ISSUE THREAD

**Issue by Zebradil** [go-task/task#1266]
### Setup

```yaml
# ./Taskfile.yml

version: "3"

tasks:
  direct:
    cmds:
      - exit 42

  indirect:
    cmds:
      - task: direct
```

### Test

```console
$ task direct --exit-code; echo $?
task: [direct] exit 42
task: Failed to run task "direct": exit status 42
42
$ task indirect --exit-code; echo $?
task: [direct] exit 42
task: Failed to run task "indirect": task: Failed to run task "direct": exit status 42
201
```

#### Expected result

```
42
42
```

#### Actual result

```
42
201
```

### Environment

- Task version: Task version: v3.27.1
- Operating system: x86_64 GNU/Linux
- Experiments enabled:

**Comment by pd93** [comment]
@Zebradil Thanks for the bug report. I've done a bit of digging and pushed up a PR: #1270. Please feel free to check it and see if it works for you.
