### ISSUE TITLE
Support command line completion on Windows

### ISSUE THREAD

**Issue by gedw99** [go-task/task#127]
anyone know if completion works on windows ?

**Comment by andreynering** [comment]
Hi @gedw99,

We currently only support completions for ZSH, see https://github.com/go-task/task/tree/master/completion

There's an issue for implementing it for Bash (#103), which is open for contributions

I think the Bash one would probably work on Git Bash for Windows, but about supporting it in cmd/PowerShell, I don't even know how to do that. So this is another thing I'll delegate to contributors

**Comment by gedw99** [comment]
Will leave open ? I don't have any time or the right skills to work on this

**Comment by andreynering** [comment]
@gedw99 Yes, let keep this open in case someone else have the knowledge and want to work on this

**Comment by andreynering** [comment]
Closing since I'm merging this issue with #103
