### ISSUE TITLE
FR: allow piping of stdin

### ISSUE THREAD

**Issue by pschuegr** [go-task/task#128]
Right now if I run a command that expects input as part of a task it seems to block.  It would be great if we could run commands that require input as well.

Would you accept a PR for this?

**Comment by pschuegr** [comment]
Apologies it seems to work, must have been the script I was calling that had problems.

**Comment by andreynering** [comment]
@pschuegr Hi, and sorry for not responding on time

If you ever find more bugs, feel free to open issues with a example Taskfile reproducing the issue, so we can understand what you're trying to do
