### ISSUE TITLE
cannot open shared object file. 'libesets_pac.so'

### ISSUE THREAD

**Issue by gander** [go-task/task#1284]
Run:
```shell
sudo snap install task --classic
task
```

Output:
```
ERROR: ld.so: object 'libesets_pac.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
task: No Taskfile found in "/home/my-user". Use "task --init" to create a new one
```

- Task version: 3.28.0
- Operating system: Linux Mint 21.2 Victoria 
- Experiments enabled: false

**Comment by gander** [comment]
Installed via `task_linux_amd64.deb` does not have this error

**Comment by andreynering** [comment]
Hi @gander,

Do you know if you distro supports classic snaps? In some cases you need to manually enable it.

Also, given your output, it looks like despite of the warning it _is_ actually working? I see `task: No Taskfile found in "/home/my-user". Use "task --init" to create a new one` there. If you try to run a real Taskfile, does it work?

**Comment by gander** [comment]
Not tested. Already on deb version

**Comment by andreynering** [comment]
I'm closing this, then. If anyway experiences the same problem, feel free to comment to let us know.
