### ISSUE TITLE
Ctrl+C and SIGTERM does nothing when `--watch` flag is used

### ISSUE THREAD

**Issue by rmmcnulty9** [go-task/task#132]
Hello, I am trying to use the `--watch` for one of my tasks but I can not stop `task` when I am done. I have to `kill -9` `task`. Am I missing something?

**Comment by andreynering** [comment]
Hi @rmmcnulty9, thanks for reporting this bug!

I plan to take a look at it soon

**Comment by andreynering** [comment]
@rmmcnulty9 Can you tell me what operating system you're using?

**Comment by grzegorz-zur** [comment]
You need to range over signals in this line https://github.com/go-task/task/blob/687b4ec8375dfa03052543f70c51364933641d2c/cmd/task/task.go#L140
I can send pull request later.

**Comment by grzegorz-zur** [comment]
There is also no call to `context.Done` method anywhere in the code.

**Comment by andreynering** [comment]
@grzegorz-zur Done os called on the sh lib. See:

https://github.com/mvdan/sh/blob/3a244a89e2e520d2777e94693d51bef800761879/interp/module.go#L81

Let me know if you need help

**Comment by rmmcnulty9** [comment]
Hello @andreynering , sorry for the slow reply. I am using Ubuntu 18.04 
HTH

**Comment by grzegorz-zur** [comment]
@andreynering It seems that in the file `watch.go` new contexts are created. The context used in signal handler is not the one used in watch mode.

**Comment by andreynering** [comment]
@rmmcnulty9 @grzegorz-zur Thanks, I was able to identify the problem: there was no `break` or `return` inside the infinite loop, so even if the context was cancelled, the program would not exit.

I fixed it by having a different signal handling to explicitly close the watcher.

**Comment by andreynering** [comment]
Let me know if you still experience problems after this fix.

**Comment by andreynering** [comment]
[v2.1.1](https://github.com/go-task/task/releases/tag/v2.1.1) is released with this fix

**Comment by rmmcnulty9** [comment]
Thanks for the quick turn around. I am very anxious to drop `make` for `task` :smile:

**Comment by christhomas** [comment]
I'm using 3.45.4 on MacOS and ctrl-c whilst using "watch:true" on a task will basically stop ctrl-c from working
