### ISSUE TITLE
Text of multi line description not aligned

### ISSUE THREAD

**Issue by kamilbiela** [go-task/task#133]
First of all, thanks for the great tool. 

It would be nice if multiline descriptions of task keep the aligment. Currently if I define Taskfile like that:
```
version: "2"

tasks:
  change-set-create:
    desc: |
      Create change set. Required vars: ENV, CHANGE_SET_NAME.
      Optional (values taken from prev): SOME_VAR
    cmds:
       - echo "123"
```
Output of task --list looks like that:

```
task: Available tasks for this project:
* change-set-create: 			Create change set. Required vars: ENV, CHANGE_SET_NAME.
Optional (values taken from prev): SOME_VAR
```
It would be really nice if it keep the indent, so its more readable:
```
task: Available tasks for this project:
* change-set-create:      Create change set. Required vars: ENV, CHANGE_SET_NAME.
                          Optional (values taken from prev): SOME_VAR
```

**Comment by andreynering** [comment]
Hi @kamilbiela, I think you're actually looking for https://github.com/go-task/task/issues/107

**Comment by kamilbiela** [comment]
@andreynering hey thanks, probably yes, but sometimes one line is not enough to describe task. I kind of wanted to have "readme" after listing the tasks. For now I just cut the description from task and moved it to help or to readme.md, so I think you can close this issue, thanks.

**Comment by andreynering** [comment]
@kamilbiela I actually think this propose also makes sense, and is complimentary to #107, so let's keep it open for now. 😉

**Comment by andreynering** [comment]
Closing this since I think the new `summary` attribute and flag is probably enough. See:

- https://github.com/go-task/task/issues/107
- https://github.com/go-task/task/pull/180
- https://taskfile.dev/#/usage?id=display-summary-of-task

**Comment by JakeSummers** [comment]
@andreynering - Would you be ok with re-opening this issue?  

The summary field is great.  

But I feel like multi-line descriptions should also be supported.  90% of my targets have a single line that can describe them but 10% need a little bit more.  My users are confused when they can't find the doc (easily) for those special targets.
