### ISSUE TITLE
ROOT_DIR is current work dir

### ISSUE THREAD

**Issue by nych** [go-task/task#1331]
It seems that in the latest version v3.30.0, the ROOT_DIR var is not working according to the documentation. Instead of pointing to the absolute path of the root Taskfile, it points to the current working directory same as USER_WORKING_DIR. It was working fine in v3.29.1.

- Task version: v3.30.0
- Operating system: 20.04 5.15.0-83-generic

**Comment by pd93** [comment]
Thanks for reporting. I can repro this. Looks like `TASKFILE_DIR` is also not working as intended.
