### ISSUE TITLE
Add "JSON Schema" support to improve experience with code editors

### ISSUE THREAD

**Issue by antonmarin** [go-task/task#135]
Have you thought about adding schema to http://schemastore.org/json/ ?

**Comment by andreynering** [comment]
Hi @antonmarin,

Thanks for the suggestion! I wasn't aware that this existed, but I liked the idea.

I'd need help with it, though, since I don't really know the JSON schema format to write one.

Also, we'd probably probably have some challenges describing a schema for it because:

- Some attributes accepts more than one "type" like either a string or an object with different keys allowed:
  - `"echo foo"`
  - `{cmd: "echo foo", silent: true}`
  - `{task: echo, vars: {VALUE: foo}}`)
- We had a format migration, and version 1 looks different from version 2. See [this document](https://github.com/go-task/task/blob/master/TASKFILE_VERSIONS.md).

I don't know if allowing different types for an attributes is supported by JSON Schema

**Comment by smyrman** [comment]
If anyone want to have a shot at this, I started scrabbling down a a schema. It's not complete or necessarily right, but it may serve as a starting point on how you could address multiple versions etc.

I am not going to spend any time completing such a schema (at least not now), but I am happy to do reviews and comment on it.

```js
{
	"anyOf": [
		{
			"title": "Taskfile v1",
			"type": "object",
			"additionalProperties": {"$ref": "#/definitions/task.v1"}
		},
		{
			"title": "Taskfile v2.0",
			"type": "object",
			"properties": {
				"version": {"type": "string", "enum": ["2", "2.0"]},
				"vars": {"$ref": "#/definitions/vars/v1"},
				"tasks":  {"type": "object", "additionalProperties": {"$ref": "#/definitions/task/v1"}} // no changes
			}
		},
		{
			"title": "Taskfile v2.1",
			"type": "object",
			"properties": {
				"version": {"type": "string", "enum": ["2", "2.1"]},
				"vars": {"$ref": "#/definitions/vars/v1"},
				"tasks":  {"type": "object", "additionalProperties": {"$ref": "#/definitions/task/v2.1"}}
			}
		},
	],
	"definitions": {
		"vars/v1":  {"$ref": "#/definitions/var/v1"}},
		"var/v1": {...},
		"task/v1": {
			"type": "object",
			"properties": {
				"vars": {"$ref": "#/definitions/vars/v1"},
				"cmds": {"type": "array", "items": {"$ref":"#/definitions/cmd/v1"}}
			}
		},
		// we don't need to repeat the v1 structure for v2.0 if there where no changes - just create new definition when
		// it's actually needed.
		"task/v2.1": { // task object is unchanged until 2.1, when "prefixed" was added and "ignore_errors" was allowed.
			"type": "object",
			"properties": {
				"vars": {"$ref": "#/definitions/vars/v1"},
				"cmds": {"type": "array", "items": {"$ref":"#/definitions/cmd/v1"}},
				"output": {"type": "string", "enum": ["interleaved", "group", "prefixed"], "default": "interleaved"}
			}
		},
		"cmd/v1": {
			"anyOf": [
				{
					"type": "string"
				},
				{
					"type": "object",
					"required": ["cmd"],
					"properties": {
						"cmd":{"type": "string"},
						"vars": {"$ref": "#/definitions/vars/v1"}
					}
				},
				{
					"type": "object",
					"required": ["task"],
					"properties": {
						"cmd":{"type": "string"},
						"vars": {"$ref": "#/definitions/vars/v1"}
					}
				}
			]
		},
		// we don't need to repeat the v1 structure for v2.0 if there where no changes.
		"cmd/v2.1": {...}, // Same as v1, but add "ignore_errors" for example...
		},
	}
}
```

**Comment by andreynering** [comment]
@smyrman Thanks for taking a first try on it!

If anyone know how to test such schema inside a code editor (like VSCode), let me know.

**Comment by hanabi1224** [comment]
Any updates on this?

**Comment by andreynering** [comment]
@hanabi1224 Sorry, but I don't plan to work on this feature for now. Contribution with this would be really welcome, though!

**Comment by paulvarache** [comment]
I have been working on a vscode extension for `task` to provide Intellisense for users. I created the schema for validating `Taskfile`s and it;s available here: https://github.com/paulvarache/vscode-taskfile/blob/master/schemas/taskfile.schema.json

This is only for v2.8, but the version can be matched and using `anyOf` automatically select the correct properties in the schema. I will add support for v3 when it comes out, but don't think I will support older version.

Unfortunately, vscode does not come with yaml validation by default. The extension yaml from RedHat adds support for this. You can use its configuration to enable the schema. The vscode extension [vscode-taskfile](https://marketplace.visualstudio.com/items?itemName=paulvarache.vscode-taskfile) configures vscode automatically, but is still experimental

**Comment by KROSF** [comment]
[Here](https://gist.github.com/KROSF/c5435acf590acd632f71bb720f685895) the schema for version 3.

**Comment by Crandel** [comment]
Hey guys, 

my MR, based on schema provided by @KROSF was just merged. It should be available  here [https://json-schema.org/json/taskfile.json](https://json-schema.org/json/taskfile.json) soon

**Comment by Geogboe** [comment]
Is anyone else getting this error in vscode? 
>Unable to load schema from 'https://json.schemastore.org/taskfile.json': No content.YAML(768)

When I reference the [gist](https://gist.githubusercontent.com/KROSF/c5435acf590acd632f71bb720f685895/raw/6f11aa982ad09a341e20fa7f4beed1a1b2a8f40e/taskfile.schema.json) @KROSF  graciously provided it works fine but vscode doesn't seem to like this one: https://json.schemastore.org/taskfile.json

Also @Crandel, this link you referenced appears to be broken https://json-schema.org/json/taskfile.json ... Thanks all! go-task is amazing btw

**Comment by Crandel** [comment]
@Geogboe this is a correct url
https://json.schemastore.org/taskfile.json

**Comment by andreynering** [comment]
Hey everybody!

I just published a new page here to mention some community projects: https://taskfile.dev/#/community

With that, I'm finally closing this issue, but feel free to keep commenting nonetheless.

Thanks specially for @KROSF, @Crandel and @paulvarache, and also for @smyrman who made the original schema, which I assume was used as groundwork for the other schemas.
