### ISSUE TITLE
Allow grouping of tasks when running `task --list --sort none`

### ISSUE THREAD

**Issue by JakeSummers** [go-task/task#1351]
Thanks for the awesome work on this project.  Looks super great.  

I am currently migrating from `make`.  In our makefile we have a _pretty ugly_ target that uses `awk` to parse the makefile and print help.  It supports grouping targets into sections, which has been pretty useful.  

Demo:

<img width="548" alt="image" src="https://github.com/go-task/task/assets/5657503/41a49df1-ec9e-4f5a-9616-e10dbe7e6d03">

I was wondering if there was any desire to add this kind grouping functionality to `task`.

**Comment by sonnysideup** [comment]
I agree, this is a great project. I currently use a `help` target as the `.DEFAULT_GOAL` in order to provide target groups and descriptions, and I think this would be a great addition to this project.

```make
# the hack i currently use
.PHONY: help
help: ## Display help
	@awk 'BEGIN {FS = ":.*##"; printf "\nUsage:\n  make \033[36m<target>\033[0m\n"} /^[a-zA-Z_0-9-]+:.*?##/ { printf "  \033[36m%-15s\033[0m %s\n", $$1, $$2 } /^##@/ { printf "\n\033[1m%s\033[0m\n", substr($$0, 5) } ' $(MAKEFILE_LIST)
```

**Comment by andreynering** [comment]
Hi @JakeSummers and @sonnysideup,

We currently sort tasks by the namespace. Isn't that enough? For example, if you have a bunch of tasks that start with `docker:` they will be shown togehter on `task --list`.

**Comment by sonnysideup** [comment]
@andreynering I just noticed the feature last night when starting to work with the includes statement. I think I get it now, thank you.
