### ISSUE TITLE
ROOT_DIR variable is not an absolute path.

### ISSUE THREAD

**Issue by wburningham** [go-task/task#1354]
- Task version: `Task version: v3.30.1 (h1:HdfCTAJDHoWL3+3RyY+o+0IK1O5xQaSBrZIq2SKOQ84=)`
- Operating system: `macOS:  Apple M1 Max`
- Experiments enabled: should be N/A (but I do have `TASK_X_REMOTE_TASKFILES=1`)

### Problem

[The documentation on Special Variables](https://taskfile.dev/api/#special-variables) says:

> ROOT_DIR | The absolute path of the root Taskfile.

But the value of `ROOT_DIR` is a relative path not an absolute path.

### Setup

```
/tmp ❯ tree
.
├── bar
│   └── taskfile.yaml
├── foo
/tmp ❯ cat bar/taskfile.yaml
version: '3'
tasks:
  default:
    cmds:
        - echo {{ .ROOT_DIR }}
/tmp ❯ cd foo/
/tmp/foo ❯ task -t ../bar/taskfile.yaml
task: [default] echo ../bar
../bar
```

Expected `/tmp/bar`. Actual `../bar`

**Comment by vmaerten** [comment]
This is working since v3.35.1
