### ISSUE TITLE
version >3.28 not found by winget - winget manifests wrong

### ISSUE THREAD

**Issue by dpprdan** [go-task/task#1355]
As reported by @Geims83 (https://github.com/go-task/task/issues/736#issuecomment-1740399558), `winget show task.task` shows version 3.28 and `winget upgrade` doesn't find any newer version. I should find version 3.30.1 by now.

The manifests for the newer version _are_ in the [winget-pkgs repo](https://github.com/microsoft/winget-pkgs/tree/master/manifests/t/Task/Task), however. Problem is, their version specifier is `v3.30.1` instead of `3.30.1`. I suspect, this is the reason they are not picked up by `winget [update|show|etc.]`. 

I cannot figure out what exact setting made this happen. @andreynering [chezmoi](https://github.com/twpayne/chezmoi/) is also using goreleaser to publish to winget and it seems to [work fine there](https://github.com/microsoft/winget-pkgs/tree/master/manifests/t/twpayne/chezmoi), so maybe you can glance something in [their config](https://github.com/twpayne/chezmoi/blob/master/.goreleaser.yaml#L288) (or anything else), which is different to yours? NB chezmoi also uses the `v` prefix on tags, so that cannot be it.

I suspect the `v` in the manifest versions is also the reason for [this error](https://github.com/go-task/task/actions/runs/5987124321/job/16240989074#step:4:126)/[`skip_upload: true`](https://github.com/go-task/task/commit/1189bdec879358e6a153a54cf8155ed569cc14f8).

**Comment by dpprdan** [comment]
Hold on, I might wrong about this... t.b.c.

**Comment by andreynering** [comment]
Closing as fixed upstream by https://github.com/microsoft/winget-pkgs/issues/121205.

**Comment by dpprdan** [comment]
@andreynering Unfortunately https://github.com/microsoft/winget-pkgs/issues/121205 only fixes this issue for past, but not present and future versions.

E.g. the [`v3.31.0`](https://github.com/microsoft/winget-pkgs/tree/master/manifests/t/Task/Task/v3.31.0) manifest issued with goreleaser was merged into the winget repo with `PackageVersion: v3.31.0`. But this needs to be `PackageVersion: 3.31.0`. This is also the case for all future versions and that is the issue that needs to be fixed here. See my OP for links to the chezmoi config, which seems to produce manifests without the `v` prefix.
