### ISSUE TITLE
Write more distinguishing error messages to console

### ISSUE THREAD

**Issue by kubaj** [go-task/task#137]
I've came to problem, where one indentation in my `Taskfile.yml` was tab instead spaces and I've had problem to find out what was the problem. I've got error message: 
```
No Taskfile.yml found. Use "task --init" to create a new one
```

It would be nice if another type of error was written to console, if yaml is invalid.

**Comment by andreynering** [comment]
Hi @kubaj, thanks for reporting

This was a recent mistake. Fixed on master
