### ISSUE TITLE
Discord channel in github template

### ISSUE THREAD

**Issue by titpetric** [go-task/task#1390]
I'm having trouble accessing the discord channel from the github template, the link may be outdated. Can some one check?

**Comment by pd93** [comment]
> Github template

Are you talking about this link?

![image](https://github.com/go-task/task/assets/9294862/aaeb49b3-9a50-4489-8ac4-44e54fa306b1)

It is working for me

**Comment by titpetric** [comment]
I'll asume it's something on discord side, thanks

**Comment by andreynering** [comment]
I just updated the link to contain the invite now.

Before, we had the channel link there, but I don't know if it worked for people not yet into our Discord server.

https://github.com/go-task/task/commit/a8d3a69013d59c963fb5794cc92f151cec2692af
