### ISSUE TITLE
Format Taskfile's per styleguide

### ISSUE THREAD

**Issue by blade2005** [go-task/task#1407]
I'd love to do something and have a Taskfile be updated to conform with the styleguide.

Not sure if this would be better as a standalone tool or something like `task --format`

I struggle a lot with ensuring Taskfile's are well formatted and are following the style guide.

**Comment by andreynering** [comment]
Hi @blade2005, thanks for opening the issue.

This is a duplicate of #265, though, so I'm closing this one.
