### ISSUE TITLE
Is there an automatic variable that contains the task name?

### ISSUE THREAD

**Issue by jmdots** [go-task/task#146]
In Makefile: `$@`

https://www.gnu.org/software/make/manual/html_node/Automatic-Variables.html

**Comment by andreynering** [comment]
Hi @jmdots,

The answer to the question is: no. Currently we don't have automatic variables.

That will probably change at some point, though. There are plans to add features to allow task templating. See #86.

**Comment by jmdots** [comment]
Thanks @andreynering!  Should I go ahead and close this?

**Comment by andreynering** [comment]
@jmdots OK, we can close this.
