### ISSUE TITLE
Feature Request: provide a bool variable to tasks that represents if the —offline flag is used 

### ISSUE THREAD

**Issue by wburningham** [go-task/task#1470]
My company is working on moving over to taskfiles for 200+ builds/apps/libraries. We rely on remote taskfiles to deduplicate build scripts. We’d like to execute logic based on whether or not a consumer uses the —offline flag. 

Examples:

1. prevent a task from running if using offline mode. Certain tasks require the latest remote taskfiles 
2. If offline disable commands in tasks that would make HTTP requests (docker pull)
3. Prompt a user for confirmation before running tasks that could benefit from pulling the latest remote taskfile

**Comment by mgbowman** [comment]
What's the expected behavior for...

```
export TASK_OFFLINE="1"
task --download --yes
```

I _think_ what will happen is ...
```
task: You can't set both --download and --offline flags
```

IMHO, in the presence of both `--download` and `--offline`, the `--offline` flag should be ignored (maybe print a info/warning message). As `--download` is a nop by design (it only downloads remote files, it doesn't execute a task), seems reasonable to me.

My use case is to always run `task`_offline_ unless it's been told to _download_ the remote taskfiles.

Thoughts?

**Comment by mgbowman** [comment]
Totally get where you're coming from, the two options are in-fact mutually exclusive. 

My previous comment was based on some CLIs I've seen that will ignore mutually exclusive options when it's trivial to interpret what the user _meant_ to do. For example, running `task --download --offline` does not make any logical sense, so I feel it would be "safe" to ignore the `--offline` flag

I guess this would work for me...

```
export TASK_OFFLINE="1"
TASK_OFFLINE="" task --download --yes
```

The use case being `TASK_OFFLINE=1` will always be set, by my devs, in my docker images, in my pipelines, but I still need to "bootstrap" by downloading the remote taskfiles.

**Comment by pd93** [comment]
How about allowing `--offline=false` on the CLI to override `TASK_OFFLINE`? This is much more explicit and allows for your use case. @vmaerten thoughts since you have an active PR?

**Comment by mgbowman** [comment]
If the cli arg overrides the env then absolutely!

This works with `v3.39.2` 
```
$ alias tasko='task --offline' # poor man's TASK_OFFLINE=1
$ tasko --offline=false --download --yes
The task you are attempting to run depends on the remote Taskfile at ...
```
