### ISSUE TITLE
Special var CLI_SILENT / CLI_VERBOSE

### ISSUE THREAD

**Issue by hans-d** [go-task/task#1480]
Like CLI_FORCE, would be great to have a CLI_SILENT and CLI_VERBOSE. This allows to play with the command verbosity.
```
cmds:
- do-x {{- if .CLI_VERBOSE }} -v {{ end -}}
- do-y | tee out.log {{- if .CLI_SILENT }} | head -n 3 {{ end -}}
```

**Comment by andreynering** [comment]
Hi @hans-d,

Agreed. This should be simple to implement, so I added the `good first issue` label in case anyone wants to contribute.
