### ISSUE TITLE
Errors finding packages 

### ISSUE THREAD

**Issue by Pbsteed** [go-task/task#149]
I'm guessing I'm making a small error any guidance would be appreciated! 

### Error on download:
`github.com/go-task/task (download)
package github.com/go-task/task/v2/internal/compiler: cannot find package "github.com/go-task/task/v2/internal/compiler" in any of:
	/usr/lib/go/src/github.com/go-task/task/v2/internal/compiler (from $GOROOT)
	/go/src/github.com/go-task/task/v2/internal/compiler (from $GOPATH)
package github.com/go-task/task/v2/internal/compiler/v1: cannot find package "github.com/go-task/task/v2/internal/compiler/v1" in any of:
	/usr/lib/go/src/github.com/go-task/task/v2/internal/compiler/v1 (from $GOROOT)
	/go/src/github.com/go-task/task/v2/internal/compiler/v1 (from $GOPATH)
package github.com/go-task/task/v2/internal/compiler/v2: cannot find package "github.com/go-task/task/v2/internal/compiler/v2" in any of:
	/usr/lib/go/src/github.com/go-task/task/v2/internal/compiler/v2 (from $GOROOT)
	/go/src/github.com/go-task/task/v2/internal/compiler/v2 (from $GOPATH)
package github.com/go-task/task/v2/internal/execext: cannot find package "github.com/go-task/task/v2/internal/execext" in any of:
	/usr/lib/go/src/github.com/go-task/task/v2/internal/execext (from $GOROOT)
	/go/src/github.com/go-task/task/v2/internal/execext (from $GOPATH)
package github.com/go-task/task/v2/internal/logger: cannot find package "github.com/go-task/task/v2/internal/logger" in any of:
	/usr/lib/go/src/github.com/go-task/task/v2/internal/logger (from $GOROOT)
	/go/src/github.com/go-task/task/v2/internal/logger (from $GOPATH)
package github.com/go-task/task/v2/internal/output: cannot find package "github.com/go-task/task/v2/internal/output" in any of:
	/usr/lib/go/src/github.com/go-task/task/v2/internal/output (from $GOROOT)
	/go/src/github.com/go-task/task/v2/internal/output (from $GOPATH)
package github.com/go-task/task/v2/internal/status: cannot find package "github.com/go-task/task/v2/internal/status" in any of:
	/usr/lib/go/src/github.com/go-task/task/v2/internal/status (from $GOROOT)
	/go/src/github.com/go-task/task/v2/internal/status (from $GOPATH)
package github.com/go-task/task/v2/internal/taskfile: cannot find package "github.com/go-task/task/v2/internal/taskfile" in any of:
	/usr/lib/go/src/github.com/go-task/task/v2/internal/taskfile (from $GOROOT)
	/go/src/github.com/go-task/task/v2/internal/taskfile (from $GOPATH)
package github.com/go-task/task/v2/internal/taskfile/read: cannot find package "github.com/go-task/task/v2/internal/taskfile/read" in any of:
	/usr/lib/go/src/github.com/go-task/task/v2/internal/taskfile/read (from $GOROOT)
	/go/src/github.com/go-task/task/v2/internal/taskfile/read (from $GOPATH)
package github.com/go-task/task/v2/internal/taskfile/version: cannot find package "github.com/go-task/task/v2/internal/taskfile/version" in any of:
	/usr/lib/go/src/github.com/go-task/task/v2/internal/taskfile/version (from $GOROOT)
	/go/src/github.com/go-task/task/v2/internal/taskfile/version (from $GOPATH)
package github.com/go-task/task/v2/internal/templater: cannot find package "github.com/go-task/task/v2/internal/templater" in any of:
	/usr/lib/go/src/github.com/go-task/task/v2/internal/templater (from $GOROOT)
	/go/src/github.com/go-task/task/v2/internal/templater (from $GOPATH)`

**Comment by andreynering** [comment]
Hi @Pbsteed,

Can you explain us better what you're trying to do? Importing Task as a library?

I think that isn't possible yet because there wasn't a release after the move to a Go Module.

Also, keep in mind use as a library is not documented and some packages are internal only for now. See #121.

**Comment by andreynering** [comment]
Ping @Pbsteed

**Comment by Pbsteed** [comment]
Apologies for the delay, I got this sorted out and closing this issue out.

**Comment by mrunali-6** [comment]
> Apologies for the delay, I got this sorted out and closing this issue out.

Hey can you please answer how you resolved it, I am facing the same issue. Thanks in advance!
