### ISSUE TITLE
panic: assignment to entry in nil map

### ISSUE THREAD

**Issue by segfault16** [go-task/task#150]
A panic is thrown when Taskfile includes other Taskfile but doesn't declare Tasks of its own.

If relevant, include the following information:
- Task version
2.2
- OS
win / linux
- Example Taskfile showing the issue
--

Taskfile.yml:
---
```
version: '2'

includes:
  other: ./OtherTasks.yml
```
--

OtherTasks.yml:
---
```
version: '2'

tasks:
  test:
    cmds:
    - ls

```

running "task" results in:

goroutine 1 [running]:
github.com/go-task/task/internal/taskfile.Merge(0xc0000ae540, 0xc0000ae600, 0xc000119aa8, 0x1, 0x1, 0x0, 0x414235)
        /home/x/gopath/src/github.com/go-task/task/internal/taskfile/merge.go:30 +0x3c6
github.com/go-task/task/internal/taskfile/read.Taskfile(0x0, 0x0, 0x725520, 0x3, 0xc000032570)
        /home/x/gopath/src/github.com/go-task/task/internal/taskfile/read/taskfile.go:45 +0x302
github.com/go-task/task.(*Executor).Setup(0xc0000c3b80, 0xc0000c3b80, 0x3)
        /home/x/gopath/src/github.com/go-task/task/task.go:81 +0x50
main.main()
        /home/x/gopath/src/github.com/go-task/task/cmd/task/task.go:109 +0x67d

**Comment by andreynering** [comment]
Hey @segfault16, thanks for reporting this error!

This is now fixed on master.
