### ISSUE TITLE
Completions don't work

### ISSUE THREAD

**Issue by sahellebusch** [go-task/task#1501]
- Task version:
```sh
❯ t --version
Task version: v3.34.1 (h1:yAAxUM54zoaHv+OtDnGgkWSVeiRuaOCn1lPUXPQQA0o=)
```

- Operating system:
Ventura 13.6.2

- Experiments enabled:
None

I've seen this is supposed to work, but when I do `t <tab>` nothing shows up. Same for `task <tab>`.

**Comment by pd93** [comment]
@sahellebusch There's not enough information here for me to reproduce your issue.

- What shell are you using?
- What steps have you tried to install completions
- etc.

Completions are working fine for me with ZSH. Please make sure to follow the [setup instructions](https://taskfile.dev/installation/#setup-completions) carefully. I'm going to close this for now.

**Comment by barrykaplan** [comment]
I'll open a new issue if need be.

I am running zsh with zimfw
all standard completions work
copied _task to ~/.zsh/completions
that directory is in fpath
restart shell

task <tab> yields nothing
