### ISSUE TITLE
task --slient --list-all with remote taskfiles causes panic

### ISSUE THREAD

**Issue by wburningham** [go-task/task#1509]
A simple repro case:

```
# Taskfile.yml
version: "3"

includes:
  scary: https://raw.githubusercontent.com/go-task/task/main/docs/Taskfile.yml
```

Pull the latest version of task:

```
$ mkdir task3.34.1
$ curl -Ls https://github.com/go-task/task/releases/download/v3.34.1/task_darwin_arm64.tar.gz | tar -xvzf - -C task3.34.1
```

Run the following

```
$ ./task3.33.1/task --silent --list-all
# OR
$ ./task3.33.1/task --yes --list-all
$ ./task3.33.1/task --silent --list-all
```

See the error

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=...]
...
```

This may be causing issues for #1406 since the [bash auto complete uses `--silent --list-all`](https://github.com/go-task/task/blob/1f477eb456c60e96ddd2cc41da8a7d3a28d78a9d/completion/bash/task.bash#L48)

Task version: 3.34.1
Operating system: macOS 14.2
Experiments enabled: `TASK_X_REMOTE_TASKFILES=1`

**Comment by pd93** [comment]
Thanks for reporting @wburningham. Fix in #1512.
