### ISSUE TITLE
task --slient --list-all with remote taskfiles stores cache in wrong directory

### ISSUE THREAD

**Issue by wburningham** [go-task/task#1514]
A simple repro case:

```
# Taskfile.yml
version: "3"

includes:
  scary: https://raw.githubusercontent.com/go-task/task/main/docs/Taskfile.yml
```

Pull the latest version of task:

```
$ go install github.com/go-task/task/v3/cmd/task@latest
```

Run the following

```
❯ task --version
Task version: v3.34.2-0.20240222002527-65fdb618aa89 (h1:gWAxMeiLdF183unxVCiUwC8m3K78iQuNR3ivbcnioXw=)

❯ tree
.
└── Taskfile.yml

❯ task --silent --list-all --yes

❯ tree
.
├── Taskfile.yml
└── remote
    ├── 8e8360457464983a90a33addd8d6fc2989d9604125dbe4250e6d979d41e37937.checksum
    └── 8e8360457464983a90a33addd8d6fc2989d9604125dbe4250e6d979d41e37937.yaml
```

**I would expect the cache to use `.task/remote` instead of `remote`.** I _think_ this is a regression, but I'm not sure.

Task version: v3.34.2-0.20240222002527-65fdb618aa89
Operating system: macOS 14.2
Experiments enabled: `TASK_X_REMOTE_TASKFILES=1`

**Comment by pd93** [comment]
Hi @wburningham, this is indeed a regression. I've got a fix on another branch, but I'll make a quick fix for just this issue shortly. Thanks for your continued testing of this functionality!

**Comment by wburningham** [comment]
@pd93 thanks for the quick turnaround!
