### ISSUE TITLE
Call --list from within taskfile.

### ISSUE THREAD

**Issue by rangerjo** [go-task/task#1562]
As a default task I wish to call `task --list`. This will display the builtin summary of all available tasks. Unfortuantly, some distros (eg. Arch) package `task` as `go-task`, so the above default task would fail. 

It would be nice to either
1. have a global Variable similar to CLI_ARGS avalible that holds `argv[0]`, or in other words the command issued to run `task`, or
2. call `task --list` from within the Taskfile just like calling any other task without exiting `task`.

**Comment by vmaerten** [comment]
Hi @rangerjo,

In the next version, a new special variable will be available (https://github.com/go-task/task/pull/1624)
TASK_EXE will hold `argv[0]`
