### ISSUE TITLE
Template-related errors are difficult to understand

### ISSUE THREAD

**Issue by QianChenglong** [go-task/task#1600]
![image](https://github.com/go-task/task/assets/1881126/fb478c66-f4c8-4766-bcf4-8eac5de65098)

**Comment by pd93** [comment]
Worth noting that the new YAML parsing won't really improve templating errors - only YAML ones. However, given that the templating library we use is built into Golang, there's not really much we can do to improve it, so I think I'm fine with this staying closed unless someone has a bright idea.
