### ISSUE TITLE
Add `q` alias for `shellQuote` template function?

### ISSUE THREAD

**Issue by vergenzt** [go-task/task#1601]
The project I'm working on right now works with a lot of files with special characters in their names. I'm passing these filenames around as variables and referring to them a lot in shell commands.

I just realized I can use the `shellQuote` function to quote things... but unfortunately that makes my commands a lot longer since I'm referring to 2-3 filename variables in each command (having to write temporary files in a pipeline into a directory containing special chars), so I'm having to repeat `{{shellQuote .VAR}}` a lot.

It'd be SOOOO nice to be able to just do `{{q .VAR}}`! Without (IMO) really any loss of clarity. Since the primary / only(?) way of actually _operating_ on the contents of variables is via shell commands, it seems appropriate to me that the `shellQuote` function should have such a short alias.

Thoughts?

**Comment by andreynering** [comment]
@vergenzt I liked the idea. Contributions welcome! This should be easy to do.

**Comment by vergenzt** [comment]
PR opened! #1603
