### ISSUE TITLE
shell opt in variables sh not working

### ISSUE THREAD

**Issue by QianChenglong** [go-task/task#1609]
<img width="2546" alt="image" src="https://github.com/go-task/task/assets/1881126/0048d63b-3cea-4959-b45f-d6eb50b0ecc8">

**Comment by trulede** [comment]
@QianChenglong Can you provide a _concise_ Taskfile that demonstrates exactly the problem.

**Comment by vmaerten** [comment]
I am closing this. If you can provide a minimal reproducing example, comment in this issue or open a new one and we will take a look
