### ISSUE TITLE
Naming conflict with taskwarrior.

### ISSUE THREAD

**Issue by gl-yziquel** [go-task/task#1672]
Hi.

I do not know what may be done or not about this, but I experience a naming conflict. go-task's task tool and taskwarrior's task tool share the same name.

I do not expect a renaming of either, but that name conflicts impacts me. I indeed use taskwarrior as a locally configured and locally set up bug tracker on my machine. Local to a git repo. I find it pretty much convenient. Until that name conflict.

I opened a bug report on Debian's Bug Tracking system.

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1071939

And on taskwarrior's github repos:

https://github.com/GothenburgBitFactory/taskwarrior/issues/3463
https://github.com/GothenburgBitFactory/taskshell/issues/75

Anyway...

Good luck with your task runner development.

Best.

**Comment by gl-yziquel** [comment]
The code below allows to set TASKBIN to define the path for the taskwarrior executable in the task shell tasksh.

https://github.com/gl-yziquel/taskshell/tree/v1.2.0-yziquel

This helps circumvent the name clash between taskwarrior and go-task for the task executables.

**Comment by pd93** [comment]
This has been discussed at length in the past. There is not much that we or the maintainers of `taskwarrior` can do about this given that both tools are well established. The number of users that have both installed is fairly small and some basic knowledge of `PATH` and aliases can help to avoid conflicts - much like the tool you linked.
