### ISSUE TITLE
Winget version is almost two months old

### ISSUE THREAD

**Issue by cstrachan88** [go-task/task#1680]
The current version on winget is 3.36.0 which is a few versions behind. I know there was a comment (linked below) that referenced a github action to keep the releases up to date. Is there a way to get this working?

> There's also a [GitHub Action](https://github.com/marketplace/actions/winget-releaser) to make things easier; the only small issue is that it needs one version of the app already on the repository, so the first upload has to be done manually.

_Originally posted by @sanzoghenzo in https://github.com/go-task/task/issues/736#issuecomment-1441429087_

**Comment by andreynering** [comment]
Hi @cstrachan88!

Thanks for reporting this.

I just opened PRs for the new releases, and they will be available as soon as Microsoft folks merge them.

- https://github.com/microsoft/winget-pkgs/pull/156700
- https://github.com/microsoft/winget-pkgs/pull/156701
- https://github.com/microsoft/winget-pkgs/pull/156702
