### ISSUE TITLE
Is it possible to provide a Web GUI?

### ISSUE THREAD

**Issue by ccxuy** [go-task/task#1686]
A web GUI as a plugin or interative part is helpful for observing and manipulating tasks, specailly when many tasks and servers involked. Some thing similar to this:
https://dev.to/yohamta/a-simple-command-tool-to-execute-dags-defined-in-yaml-built-with-go-4l4j

**Comment by pd93** [comment]
I can't see this being added to the main Task repo right now. There is simply too much other work to do and not enough time to maintain a substantial feature like this. This has been discussed before and I believe @titpetric created a community project: https://github.com/titpetric/task-ui.

This could be revisited in the future, but I'm going to close this for now.
