### ISSUE TITLE
Can no longer find reference to the global env vars in the documentation

### ISSUE THREAD

**Issue by toby-griffiths** [go-task/task#1703]
I've just come to look up the global env vars available to tasks on https://taskfile.dev, but I see that the docs have been updated, and I can no longer find reference to these.

Example varas…
- The task name (.TASK)
- The directory of the task file
- The directory of the root task file

Have these dissappeared from the docs?

Sorry if this is the wrong repo for this issue.  I looks for a docs repo, but couldn't find one.

**Comment by toby-griffiths** [comment]
And of course… as soon as I post this I find it at https://taskfile.dev/reference/templating/

Sorry.  Closing.

**Comment by pd93** [comment]
Hey, no problem! A few bits of documentation got refactored in the last release. Hopefully the new docs are better, but it dos mean that some things have moved. Sorry for any confusion :)

**Comment by toby-griffiths** [comment]
> Hey, no problem! A few bits of documentation got refactored in the last release. Hopefully the new docs are better, but it dos mean that some things have moved. Sorry for any confusion :)

Ah.  Glad it wasn't just me going mad.
