### ISSUE TITLE
Add a feature list to the docs

### ISSUE THREAD

**Issue by alexec** [go-task/task#1722]
I'd like to have a complete list of features so I can compare to other software like Tilt, DevSpace, Goreman, Kit etc.

- UI (Tilt has this, good for new developers)
- Terminal muxing
- Task dependencies, DAG
- Probes
- 1st class Docker or K8s support

**Comment by pd93** [comment]
I don't really understand what you're asking for. Task is fundamentally nothing like the other tools you've mentioned - It's just a task runner. It also has none of the features you've listed apart from dependencies.

Also there is already a [features section](https://taskfile.dev/#features) on the website/README. This might be in need of updating, but without a valid/specific request, I'm closing this.

**Comment by alexec** [comment]
Thank you! You have answer my question just fine.
