### ISSUE TITLE
Errors with taskfile and windows

### ISSUE THREAD

**Issue by JCHacking** [go-task/task#1723]
I have a Taskfile which I want to be compatible with both windows and linux, for this I have done the following:
```yaml
task:
  cmds:
      - cmd: |
          AUTHOR_NAME=""
          AUTHOR_EMAIL=""
          if [ -n "${AUTHOR_NAME}" ] && [ -n "${AUTHOR_EMAIL}" ]; then
            export GIT_COMMIT_AUTHOR="${AUTHOR_NAME} <${AUTHOR_EMAIL}>"
          fi

          semantic-release --strict version
          semantic-release --strict publish
        platforms: [ linux ]
      - cmd: |
          (
            for /f "tokens=*" %%a in ("git config user.name") do (set AUTHOR_NAME=%%a)
            for /f "tokens=*" %%a in ("git config user.email") do (set AUTHOR_EMAIL=%%a)

            if "%AUTHOR_NAME%" neq "" if "%AUTHOR_EMAIL%" neq "" (
              set GIT_COMMIT_AUTHOR="%AUTHOR_NAME% <%AUTHOR_EMAIL%>"
            )

            semantic-release --strict version
            semantic-release --strict publish
          )
        platforms: [ windows ]
```
Whether writing the windows part in powershell or in batch I run into sh validations with errors like `"for foo" must be followed by "in", "do", ;, or a newline`

Is there any way to avoid these pre-validations for windows systems? Unfortunately I can't use Linux, WSL or git bash and I would like a more solid alternative to use commands in windows.

- Task version: 3.37.2
- Operating system: Windows
- Experiments enabled: False

**Comment by pd93** [comment]
Taskfile does not directly invoke bash/powershell on your system. Instead it uses a cross-platform shell written in Go called [gosh](https://github.com/mvdan/sh). The syntax of this shell is POSIX/bash compliant, so you should use this syntax regardless as to whether you're on Windows or Linux.

One problem you might encounter when trying to write cross-platform tasks is that `gosh` does not include some coreutils (e.g. `cp`, `rm`, `ls` etc.) that you might be used to using on unix-like systems (#197, https://github.com/mvdan/sh/issues/93) and so the commands available can vary between systems.

If you really want to use Powershell on Windows, you can invoke it manually at the start of your command. e.g.

```yml
my-task:
  cmds:
    - "powershell <my_powershell_cmd>"
```

**Comment by JCHacking** [comment]
> Taskfile does not directly invoke bash/powershell on your system. Instead it uses a cross-platform shell written in Go called [gosh](https://github.com/mvdan/sh). The syntax of this shell is POSIX/bash compliant, so you should use this syntax regardless as to whether you're on Windows or Linux.
> 
> One problem you might encounter when trying to write cross-platform tasks is that `gosh` does not include some coreutils (e.g. `cp`, `rm`, `ls` etc.) that you might be used to using on unix-like systems (#197, https://github.com/mvdan/sh/issues/93) and so the commands available can vary between systems.
> 
> If you really want to use Powershell on Windows, you can invoke it manually at the start of your command. e.g.
> 
> ```yml
> my-task:
>   cmds:
>     - "powershell <my_powershell_cmd>"
> ```

Although what you say is true, my problem is not that the commands such as rm, cp, etc. are different.

My problem is that I can not put a small script as in the example
Is there any way to launch the command directly? Why to make so many previous validations? Why not give an option to keep it simple by simply substituting variables and launching the command?

It seems that even though this is the compiled for windows, the restriction that cmd has to be in POSIX/bash breaks the concept of multiplatform.

**Comment by pd93** [comment]
It is not a restriction. You are able to run Powershell if you want to. It just needs to be invoked as mentioned. However, the whole point of using `gosh` is that you don't need to write separate scripts for Windows/Linux in the majority of cases. It is multi-platform _because_ the shell works on both platforms rather than requiring you to write the same task twice in two different shell languages.

Have you tried just removing the `platform: linux/windows` and running the task you have for Linux on Windows? I see no reason why it shouldn't work.

**Comment by JCHacking** [comment]
Ouu you are absolutely right, I didn't think of taskfile this way. This approach is a marvel!

I have seen a problem but it is with the semantic relese implementation for python, I will do a PR to fix it but it is nothing that matters here for this issue.

**Comment by pd93** [comment]
> The only drawback I see with this approach is the lack of applications, since writing in bash something you want to run on windows will surely fail for lack of commands like awk, grep, cp, etc.

Agreed. The absence of some coreutils/builtins on some platforms is a known restriction and something we plan to address in the future (#197, https://github.com/mvdan/sh/issues/93, https://github.com/mvdan/sh/issues/97).

In the meantime, it is possible to work around some of these issues by using the `{{OS}}` command in templates or the `platforms` keyword.
