### ISSUE TITLE
Is it expected that timestamp comparisons do not work for files with spaces in name?

### ISSUE THREAD

**Issue by radcool** [go-task/task#176]
I've been using Task for a while now (really like it by the way!) and I've run into an issue with regards to the "preventing unnecessary work" feature. I've noticed that if the filename in my sources or generates contains spaces, then the time comparison doesn't work. I've narrowed it down to the fact that a file called `file name with spaces.txt` will finally expand to just `file` as it traverses _func (t *Timestamp) IsUpToDate()_ -> _glob(t.Dir, t.Sources)_ -> _execext.Expand(g)_ where the filename is split into fields and only **fields[0]** is returned.

Is this a bug, or just a (known) limitation of Task? (i.e. am I currently supposed to be able to use spaces in filenames or is this just something that is not supported for the moment?)

Thanks!

**Comment by andreynering** [comment]
Hi @radcool,

Nice to know Task have been useful o you! 😉

This issue with spaces on file names was indeed a bug, and it should be now fixed on master.

Thanks for opening this issue!

**Comment by radcool** [comment]
Yep, all good now. Thanks!
