### ISSUE TITLE
How to escape Go template in a docker inspect command

### ISSUE THREAD

**Issue by imranansari** [go-task/task#179]
How can I escape Go template in commands like docker inspect 
So that `Task` can skip evaluating it ?

```shell
docker inspect -f "{{json .Config.Labels }}" \
{{.DOCKER_IMAGE_FULL_NAME}}:{{.DOCKER_IMAGE_TAG}} | jq
```
Output error:
```template: :1: function "json" not defined ```

**Comment by andreynering** [comment]
Hi @imranansari,

Unfortunately, Go doesn't have a very clean way of doing that, but you can do it [like this](https://stackoverflow.com/a/17642427).

**Comment by imranansari** [comment]
@andreynering thank you!
