### ISSUE TITLE
Unexpected logging of experiments usage

### ISSUE THREAD

**Issue by rektdeckard** [go-task/task#1805]
I am using Task as an embedded runner in a larger CLI application, which is built on [`urfave/cli/v3`](https://github.com/urfave/cli). Whenever a help or Usage is printed in the app, I see the following text preceding my expected Usage text on stdout:

```
tobiasfried@slate livekit-cli % lk --help
Usage of experiments:
  -d, --dir string        Sets directory of execution.
  -t, --taskfile string   Choose which Taskfile to run. Defaults to "Taskfile.yml".
NAME:
  (expected help text)
```

This happens even when running completely unrelated actions that do not call into any task-related code, attempt to parse or run any taskfiles, etc.

- Task version: 3.39.0
- Operating system: macOS
- Experiments enabled:

**Comment by rektdeckard** [comment]
FWIW, I am not setting any `TASK_X_` environment variables, nor using any experiments explicitly.

**Comment by vmaerten** [comment]
Hello!

Thanks for reporting! I'll take a look

**Comment by rektdeckard** [comment]
Appreciate it!

**Comment by vmaerten** [comment]
It'll be available in the next release.
You can test it by using the version from main.
