### ISSUE TITLE
[3.39.0] Autocomplete throws error

### ISSUE THREAD

**Issue by Firesphere** [go-task/task#1813]
The autocomplete, as per the documentation, add `eval "$(task --completion zsh)"` to .zsh, throws an error:
```
_arguments:comparguments:327: can only be called from completion function
```

- Task version: 3.39.0
- Operating system: MacOS Sonoma Latest using ZSH
- Experiments enabled: n/a

**Comment by orsinium** [comment]
Same problem

* `task --version`: `Task version: v3.39.0 (h1:Loe6ppP1x38Puv1M2wigp91bH/garCt0vLWkJsiTWNI=)`
* `uname -a`: `Linux serenity 6.8.0-41-generic #41-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug  2 20:41:06 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`
* `zsh --version`: `zsh 5.9 (x86_64-ubuntu-linux-gnu)`

**Comment by orsinium** [comment]
The second installation option described in the docs works (with a few extra steps to be able to write it from non-root user):

```
sudo touch /usr/local/share/zsh/site-functions/_task
sudo chmod 777 /usr/local/share/zsh/site-functions/_task
task --completion zsh  > /usr/local/share/zsh/site-functions/_task
```

**Comment by vmaerten** [comment]
It'll be fixed by : https://github.com/go-task/task/pull/1809

**Comment by vmaerten** [comment]
We will release a patch for somes fixes soon (including this one)
