### ISSUE TITLE
TASK_X_ENV_PRECEDENCE is broken

### ISSUE THREAD

**Issue by lukejoshuapark** [go-task/task#1829]
- Task version: 3.39.2
- Operating system: Linux (inside container)
- Experiments enabled: TASK_X_ENV_PRECEDENCE

Please see this reproduction of the issue: https://github.com/lukejoshuapark/task-env-issue-reproduce

When executing `./run.sh`, I would have expected to see

```
task: [dir1:run] echo $FOO $BAR
Hello World
task: [dir2:run] echo $FOO $BAR
Hello World
task: [dir1:run] echo $FOO $BAR
Hello World                                        # Note this correctly says "Hello World"
task: [dir2:run] echo $FOO $BAR
World World
```

But instead, I am seeing

```
task: [dir1:run] echo $FOO $BAR
Hello World
task: [dir2:run] echo $FOO $BAR
Hello World
task: [dir1:run] echo $FOO $BAR
World World                                      # Why has $FOO been modified in the scope of dir1???
task: [dir2:run] echo $FOO $BAR
World World
```

This may not be the simplest form of the reproduction but it mimics the scenario under which I experienced it.

**Comment by mgbowman** [comment]
I think what you're seeing is expected behavior as global / file-level [variables](https://taskfile.dev/usage/#variables) are not scoped. 

If you move the `env` declaration to `dir2:run` task level, it should work as expected.

**Comment by lukejoshuapark** [comment]
@mgbowman thanks for that, I thought they were scoped to the file they were defined in.
