### ISSUE TITLE
Add Taskfile.yaml default file name alternative

### ISSUE THREAD

**Issue by lalloni** [go-task/task#183]
Currently Task searches for Taskfile.yml as the default taskfile name.

I, as a developer, would like Task to use Taskfile.yaml as a valid alternative Taskfile name so I can have uniformity with other YAML files used by other tools and name all with the same .yaml extension instead of using .yaml for all except Taskfile.yml.

**Comment by andreynering** [comment]
Closing this issue.

Reasoning here: https://github.com/go-task/task/pull/184#issuecomment-552246185

**Comment by andreynering** [comment]
FYI: We are about to allow `.yaml` as extension soon as part of #584 and #621.
