### ISSUE TITLE
Add a `numCPU` function similar to `OS` and `ARCH`

### ISSUE THREAD

**Issue by andreynering** [go-task/task#1887]
Idea came from [this Discord thread](https://discord.com/channels/974121106208354339/1299182727089619005).

The function should return the result of [`runtime.NumCPU()`](https://pkg.go.dev/runtime#NumCPU).

Remember to update this table [on the documentation](https://taskfile.dev/reference/templating/#task-functions).

**Comment by Amoghrd** [comment]
Hey,
I have opened the above PR for this issue. PTAL and let me know if any changes are required. TIA!
