### ISSUE TITLE
go-task --version unknown

### ISSUE THREAD

**Issue by YurBoiRene** [go-task/task#1889]
```console
$ go-task --version
Task version: unknown ()
```

- Task version: 3.39.2 (from `dnf info go-task`)
- Operating system: Fedora 40
- Experiments enabled: None

**Comment by vmaerten** [comment]
This installation method is maintained by the community (cf : https://taskfile.dev/installation/#fedora). We don't know how they build it.
You need to ask them.

**Comment by YurBoiRene** [comment]
Opened an [issue](https://bugzilla.redhat.com/show_bug.cgi?id=2322459) in Fedora/Red Hat's issue tracker/

**Comment by YurBoiRene** [comment]
Fedora maintainer fixed it for Fedora 42 :)
