### ISSUE TITLE
Failed to run task "migrate": 1:35: a command can only contain words and redirects

### ISSUE THREAD

**Issue by danil-sidorov** [go-task/task#206]
- Task version master
- Windows 7

version: '2'
tasks:
  migrate:
    cmds:
      - migrate -database mysql://root@tcp(localhost:3306)/gsnode -source file://migrate up

Library golang-migrate/migrate

runs in the terminal
migrate -database mysql://root@tcp(localhost:3306)/gsnode -source file://migrate up
OK!

**Comment by danil-sidorov** [comment]
The characters need to be escaped

**Comment by davinkevin** [comment]
For newcomers, how did you escape this? 

I would like to run this command:

```
  openshift:bar:
  - cd (mktemp -d)
```

And I have the same error.

Note, the script is valid, it's using `fish` shell.

**Comment by andreynering** [comment]
@davinkevin Keep in mind that Task uses a Bash interpreter. So it does not matter if your terminal is Fish; on Taskfiles, Bash should be assumed.

What if you try `cd $(mktemp -d)`?

**Comment by davinkevin** [comment]
Thank you! It was it… 

I though `task` uses the underlying shell. I'm a bit sad to not be able to use my favorite fish shell syntax… but anyway, it works! 

Hugh 👏 for task, it's a very good product, I've discovered it lately and I think it will be one of my main tool for my day to day job 😇.
