### ISSUE TITLE
Definitions Update to Windows Defender reporting Trojan:Win32/Bearfoos.A!ml

### ISSUE THREAD

**Issue by iainsgillis** [go-task/task#210]
- 64-bit Task 2.5.2 installed via scoop on Windows 10.0.18362 Build 18362; everything was fine until this afternoon

- Virustotal reports 1 engine detecting this file https://www.virustotal.com/gui/file/117f766920c2bf3569b6f8df02618fdf74a4ecec5f112a31c60ac5a3d1685bf8/detection

- Virustotal reports all clear on the archive https://www.virustotal.com/gui/url/6c6297e292b0491b1006737fbf040b66df858261af79128e5b9cb48496540e9d/detection

- I am of the opinion that this is a false positive: I have submitted a request to Microsoft Security Intelligence; a final determination is pending, but current detection for 'client' and 'cloud' are both reported as "no malware detected."

- Definition Version 1.293.2723.0 already seems to detect no threat.

- See also https://github.com/courupteddata/Scheduler/issues/28, perhaps?

- I'll comment on this issue when I get an update from Microsoft.

**Comment by iainsgillis** [comment]
- Microsoft's final determination: Not malware

- Marking this as closed; clearly a false positive.

**Comment by andreynering** [comment]
@iainsgillis Thanks for posting here! And glad Microsoft recognized the problem.
