### ISSUE TITLE
Help with escaping characters

### ISSUE THREAD

**Issue by matthew-hollick** [go-task/task#222]
I'm having a hell of a time trying to set an environment variable. I cant get the following to work:

`AWS_VPC_ID: {sh: aws ec2 describe-vpcs --filters "Name=tag:Env,Values=staging" "Name=tag:Name,Values=mdtp_vpc" --output text --query 'Vpcs[0].VpcId'}`

Any suggestions for how to escape things would be appreciated.

**Comment by andreynering** [comment]
Hi @matthew-hollick,

It seems to work if you put it on its own line:

```yaml
AWS_VPC_ID:
  sh: aws ec2 describe-vpcs --filters "Name=tag:Env,Values=staging" "Name=tag:Name,Values=mdtp_vpc" --output text --query 'Vpcs[0].VpcId'
```
