### ISSUE TITLE
undefined: interp.EnvFromList

### ISSUE THREAD

**Issue by frederikhors** [go-task/task#230]
If relevant, include the following information:
- I'm trying to install Task with `go get -u -v github.com/go-task/task/cmd/task`
- OS: Mac OS 10.14
- Go version: go1.12.7 darwin/amd64

It gives me this error:

```log
# github.com/go-task/task/internal/execext
/Users/fred/go/pkg/mod/github.com/go-task/task@v2.2.0+incompatible/internal/execext/exec.go:44:14: undefined: interp.EnvFromList
```

**Comment by andreynering** [comment]
Hi @frederikhors,

I couldn't reproduce this. I'm also on macOS and running go1.12.7 darwin/amd64.

Are you using Go Modules or GOPATH to compile? I've being using Go Modules for a while, but in my machine it also compiles using GOPATH.

Also, I'd say that, unless you are willing to contribute to Task, I recommend one of the installation methods described here: https://taskfile.dev/#/installation

**Comment by frederikhors** [comment]
> Are you using Go Modules or GOPATH to compile?

GO MOD

**Comment by andreynering** [comment]
Hi @frederikhors, I could finally reproduce this error (happened on Travis for me).

The problem is that it seems you won't be able to use `go get` to install Task when using modules. Clone the repository and run `go install -v ./cmd/task` instead. Or use one of the other installation methods.

**Comment by jiusanzhou** [comment]
@frederikhors If you must use go mod to install, you should run `go get github.com/go-task/task/v2`
