### ISSUE TITLE
McAfee deleting task.exe on Windows Desktop

### ISSUE THREAD

**Issue by FilBot3** [go-task/task#257]
Task Version: `v3.0.0-preview2`
OS Version: `Windows 10 Enterprise 1809 17763.805`
Example Taskfile: N/A

On Windows with McAfee and other security applications, it seems to be deleting the `task.exe` before I get a chance to actually use it. I believe this is because the security applications see it as a non-signed binary and potentially dangerous? Is there any chance that could be added to the end results? I have no clue how to go about doing that and just saw that nvm for windows had to do that to make it so their binary wouldn't get deleted immediately. 

https://github.com/coreybutler/nvm-windows#antivirus

**Comment by predatorian3** [comment]
Seems its more CylanceProtect than McAfee.

**Comment by andreynering** [comment]
Hi @predatorian3, thanks for opening this issue!

Unfortunately, I also have no idea on how to proceed with this problem. So, if anyone reading this issue know what to do, let me know!

**Comment by predatorian3** [comment]
I'm not sure if this would work for the product, but this was somethign I found.

* https://stackoverflow.com/questions/51717409/is-there-any-way-to-sign-the-windows-executables-generated-by-the-go-compiler
* https://docs.microsoft.com/en-us/windows/win32/seccrypto/signtool
* https://docs.microsoft.com/en-us/windows/win32/seccrypto/cryptography-tools

Seems Cylance also deleted a vast majority of the Golang Development Kit binaries that are needed to do anything.

**Comment by andreynering** [comment]
@predatorian3 Thanks for the info!

> Seems Cylance also deleted a vast majority of the Golang Development Kit binaries that are needed to do anything.

Seems this is not a Task-specific issue then. For this reason, I'm not sure if it's worth the effort to setup the build/release tools to sign Windows binaries (I think that few people will be affected).

I'll keep this issue open for now. If anyone else is also suffering due to this issue, people comment so we know this is a widespread issue!

**Comment by predatorian3** [comment]
To use this at my place of work, I had to submit a request to my security team with the SHA256 Hash of the executable, and have them whitelist it. Still a pain, but it is a solution if the use of `signtool` can't be completed.

**Comment by predatorian3** [comment]
This is the line that CoryButler had used, but he also has a signed, "trusted" certificate. 

https://github.com/coreybutler/nvm-windows/blob/master/build.bat#L21-L22

**Comment by andreynering** [comment]
Closing some old issues...

I don't have enough time or desire to research and setup these workarounds. I see this as a problem with the antivirus software itself...
