### ISSUE TITLE
How to handle quotes in variables?

### ISSUE THREAD

**Issue by matthijskooijman** [go-task/task#259]
I'm including variables as part of the commands run by task. However, these variables can of course contain special characters for the shell. To prevent those from being interpreted, I can put quotes around the variable expansion, which get then passed to the shell. However, my variables can of course contain quotes themselves, which break out of the quotes in the Taskfile.

Is there some way to handle this? Shells handle this by not interpreting quotes inside variables expanded inside quotes (e.g. `echo $FOO` gets expanded and then word-splitted, but `echo "$FOO"` gets word-split first and then expanded, I think). For task this is probably more tricky, since (I assume) variable expanding and word-splitting/shell expansion are separate processes.

To illustrate, here is an example taskfile that tries no quoting, single quoting and double quoting. None of these allow both single quotes and doublequotes to remain unprocessed inside a variable, and unmatched quotes even make the task execution fail entirely.

```
$ cat Taskfile.yml 
version: '2'

tasks:
  test:
    cmds:
      - echo {{ .TEST }}
      - echo "{{ .TEST }}"
      - echo '{{ .TEST }}'
$ task test TEST="'foo'"
echo 'foo'
foo
echo "'foo'"
'foo'
echo ''foo''
foo
$ task test TEST='"foo"'
echo "foo"
foo
echo ""foo""
foo
echo '"foo"'
"foo"
$ task test TEST='foo"bar'
echo foo"bar
task: Failed to run task "test": 1:9: reached EOF without closing quote "
$ task test TEST="foo'bar"
echo foo'bar
task: Failed to run task "test": 1:9: reached EOF without closing quote '
```

This uses task installed from git master today (so I presume https://github.com/go-task/task/commit/0494d7ebe31c787fbd634a47ee60b04a07f0c702), on Ubuntu Disco.

**Comment by andreynering** [comment]
Hi @matthijskooijman, thanks for opening this issue!

You're right that Task templating and Shell execution are two separated steps.

Sanitizing the quote by using `\"` instead of `"` does the trick on most cases:

```bash
$ task echo TEST="foo\'bar"
echo foo\'bar
foo'bar
echo "foo\'bar"
foo\'bar
echo 'foo\'bar'
task: Failed to run task "echo": 1:15: reached EOF without closing quote '

$ task echo TEST='foo\"bar'
echo foo\"bar
foo"bar
echo "foo\"bar"
foo"bar
echo 'foo\"bar'
foo\"bar
```

I think that perhaps having a `sanitize` function would do the trick:

```yaml
tasks:
  echo:
    cmds:
      - echo "{{sanitize .TEST}}"
```

It'd do stuff like converting quotes, etc. What do you think?

**Comment by matthijskooijman** [comment]
> Sanitizing the quote by using \" instead of " does the trick on most cases:

Yeah, that would work but IMHO place the responsibility in the wrong place (and makes it way too easy to forget). But I suspect you were just showing that this would work, rather than suggestion this as a solution.

> I think that perhaps having a sanitize function would do the trick:

I guess that would be a practical solution. It's a bit of a hassle, but it would at least put the responsibility in the right place (at whoever is designing a commandline).

I wonder if "sanitize" is a good name, though. That suggests that there is a generic concept of a "sanitized" value, but what is sanitary highly depends on the context where you use it. Additionally, you're not actually really sanitizing anything, you're *encoding* a value for use in a specific context (double-quoted shell string literal in this case).

In this case, the scope of such a function should probably be specific and limited to exactly that (escaping/encoding an arbitrary string for use in a doublequoted string literal). The name should probably reflect this, though it might be hard to find something concise.

One thing that could help is to do the encoding *and* the quoting itself as part of the same function, e.g.:

      - echo {{shell-quote .TEST}}

Then a `shell-quote` function has the responsibility of producing a valid quoted string literal, with whatever encoding is needed to make it work. The downside here is that it is not possible to include multiple variables in a single quoted string (though that might not be relevant, if you put two string literals directly after each other without spaces, they will become a single argument anyway).

**Comment by andreynering** [comment]
@matthijskooijman I liked the `{{shellQuote .TEXT}}` idea!

**Comment by justafish** [comment]
Fixed in https://github.com/go-task/task/releases/tag/v3.9.0 :tada:

**Comment by matthijskooijman** [comment]
Cool, thanks. When I remember what project I was running into this issue, I'll be sure to test the implementation :-)

Still some remarks about this:
 - The release notes talk about `shellQuote`, but the documentation has `Quote` (and AFAICS the code seems to accept anything starting with `Q`?).
 - When reading the documentation, I was missing a description of what quoting is applied exactly (e.g. that it would add double-quotes and escape all doublequotes with backslashes, that kind of thing). Reading the code, I see that a number of different quoting strategies are implemented, using single quotes, double quotes or `$'` depending on the exact string to be quoted. The documentation already mentions "The quoting strategy is chosen on a best-effort basis, to minimize the amount of extra bytes necessary. ", but maybe it would be good to describe the potential quoting strategies briefly?
 - The quoting function really seems well-done, with implementations for different cases and language variants. Better than most implementations out there :-)
