### ISSUE TITLE
Setup bash & zsh autocomplete as part of brew install

### ISSUE THREAD

**Issue by bfarayev** [go-task/task#264]
Now that we have bash & zsh autocomplete scripts in this repo, we can install them as part of installation with homebrew.

I've noticed that we have this formula already: https://github.com/go-task/homebrew-tap/blob/master/Formula/go-task.rb

Adding 2 lines to the formula, will do that for us:
```
    bash_completion.install "completion/bash/task.bash" => "task"
    zsh_completion.install "completion/zsh/_task" => "_task"
```
I was just testing this on my machine today. Happy to raise a PR for that if it's fine.

Thanks

**Comment by andreynering** [comment]
Hi @bfarayev,

Yeah, it'd be nice to have that. Contributions would be welcome. 🙂 

We'd probably have to adapt our Goreleaser setup to also include these completion scripts on the `.tar.gz` files.

Also, we need to make sure that it won't break stuff for users that try install an older version (without the completion scripts in the tarball).

**Comment by andreynering** [comment]
Some additional instructions on how to do it was added by @zx8 here: https://github.com/go-task/task/issues/382#issue-713577257

Contributions with this are welcome!

**Comment by notnmeyer** [comment]
hey @bfarayev! i opened a PR for this, but im not sure how to go about testing it. would love to hear a little about how you tested.

**Comment by bfarayev** [comment]
hey @notnmeyer! I guess the best way to test is to remove task from your system (Eg: on Mac you'd do `brew uninstall task`) first. Assuming that you're making a change into the Homebrew formula in your own fork, install that formula and see if it installs bash/zsh completion as part of it. Delete and make changes to your formula until it works and when ready, PR to the upstream.

**Comment by notnmeyer** [comment]
thanks @bfarayev, i think what i probably worded my question poorly. i was looking for tips on how to install from the tap in my fork, that's the part that seems non-obvious.

**Comment by bfarayev** [comment]
ah sorry for the late answer. glad that you figured it out.

I think the best ways to test the changes to the tap (Eg the PR you're doing to go-tasks's main homebrew-tap in [this PR](https://github.com/go-task/homebrew-tap/pull/2)) is to fork that repo, make your own tap and then in your local machine, remove everything related to task, "brew tap" your forked tap which will include the autocompletion scripts change and see what you get when you say something like this:

```
brew tap notnmeyer/go-task
brew install go-task ?
```

or directly use 
```
brew install notnmeyer/tap/go-task
```
(something along these lines will work). 

Check this out as well to see how it works: https://docs.brew.sh/Taps

Hope it helps

**Comment by bfarayev** [comment]
I also found some notes on how to update the formula in the project docs: https://taskfile.dev/#/releasing_task?id=homebrew

**Comment by andreynering** [comment]
Implemented as part of https://github.com/go-task/task/pull/592.

We should have completions when installing via Brew starting in the next release.
