### ISSUE TITLE
Transpile to Makefile

### ISSUE THREAD

**Issue by aegershman** [go-task/task#267]
In order to placate work colleagues who might gripe about having to install more binaries to get buildscripts to work, perhaps a Taskfile.yml could transpiled to a Makefile equivalent, which could then be checked into source control alongside the original Taskfile.yml

This is a total whim, it's not a seriously thought out usecase, let alone considered if it's really even possible... But still, thought I'd at least put it out here. Feel free to close whenever, otherwise I'll close it out in a few days myself. Thanks for all you all do 👍 

EDIT nah I'll just close it now

**Comment by andreynering** [comment]
Hi @aegershman,

A discussion about transpiling to Makefiles was raised in the beginning of this project. We decided to not proceed with that.

Unfortunately, it'd not be that easy. And Task supports some features that Make doesn't (and vice-versa) which means it'd only half work.

**Comment by aegershman** [comment]
Right, I gotchu; I'm sure it'd introduce unnecessary complexities and an incomplete equivalent feature set that'd hold back the potential of Task, etc. I'm not _sure_ totally why I felt compelled to post the issue even while knowing all these things and it not being an especially compelling use-case, but alas 🤷‍♂

Thank you 👍
