### ISSUE TITLE
Upgrade Sprig in master and Slim-Sprig in v3

### ISSUE THREAD

**Issue by smcstewart** [go-task/task#290]
Task version: Both master branch and Preview2.
OS: MacOS, but irrelevant
Enhancement / Update

It'd be great to get an update to sprig to include the "get" dict function which was released in 3.0.2 in Dec, or perhaps an update to the docs to define which functions are / are not supported from sprig.

**Comment by andreynering** [comment]
Hi @smcstewart, thanks for the reminder!

I indeed want to do that.

(FYI, on v3/Preview we're actually using [Slim-Sprig](https://github.com/go-task/slim-sprig) now).

**Comment by smcstewart** [comment]
Aha! Not sure if it makes sense then to update to the latest Sprig for 2.x version - that's your call. Am currently just using ```pluck "var" $dict | first``` which does the job. I will await v3.

**Comment by andreynering** [comment]
This should be now available in the recently-released v3
