### ISSUE TITLE
Make task hidden from user, but callable from inside the Taskfile

### ISSUE THREAD

**Issue by stevenkl** [go-task/task#295]
This might be useful for tasks preparing something, called from multiple other tasks.
Hiding the task from the user, eg. its not callable like `task <hidden_task>`, when the preparing stuff is not useful on its own.

**Comment by andreynering** [comment]
Hi @stevenkl,

You mean, like, private tasks? That was proposed before on #284.

I don't have a string opinion on it.

**Comment by stevenkl** [comment]
Hello @andreynering,

just exactly like described in #284.
In the other Hand, we could usw a simple multiline script in a variable. But this meens We must call it every time. With a hidden task we can use its features like status or preconditions, also source and generates.

But i also think the user oft my Taskfile should be able to see that there is another, hidden/private task runnable.

As i think of it, is there an option to use a variable as precondition?
For example a `RUN_IT: true` for the hidden task and a simple precondition to evaluate that.

**Comment by andreynering** [comment]
> As i think of it, is there an option to use a variable as precondition?
> For example a `RUN_IT: true` for the hidden task and a simple precondition to evaluate that.

Can you elaborate on that? I couldn't get what you mean.

**Comment by stevenkl** [comment]
Hello again,

my initial thought was to hide some tasks that do the heavy lifting and just export some control tasks.
Think of it just like a module in go with exported members.

I'm trying to use these Taskfiles as an interface for configuring and deploying our internal services and applications.

I want our employees to just hit `task install` or `task update start` without knowing what exactly is needed to do. Especially for a task like update, that is preparing containers and volumes to be saved/exported/what else in the background. It's just an example, but i hope you get what i mean.


But currently i don't know if this is enough for my use case. It might be also a practical idea to share some state between tasks. Something like mutable global vars, for example. But that's another story 😉

**Comment by tommyalatalo** [comment]
I second this request, there are definitely use cases for importing a taskfile and having only some of the tasks exposed while some are hidden private/support tasks.

**Comment by stephencheng** [comment]
hi @stevenkl , you may want to have a look of https://github.com/upcmd/up, it's designed to support Public tasks and inner tasks, and inter tasks is callable. 

What you only need to do is to use Capital letter for public task

Also, you may want to use the feature of module to draw the boundary of reusable module and consumer part

**Comment by tylermmorton** [comment]
Is this issue OK to close with the suggested workaround and the duplicate mentioned in #284?

**Comment by kerma** [comment]
This is now covered with the help section and `--list-all` flag: https://github.com/go-task/task/blob/master/docs/usage.md#help

Please file a new issue if you feel like the docs need work on this.
