### ISSUE TITLE
Command 'task --version' is printing on standard error file descriptor

### ISSUE THREAD

**Issue by lboulard** [go-task/task#299]
Running those commands show that version string is not on standard output (stdout).

```shell
$ task --version
Task version: 2.8.0
$ task --version >/dev/null
Task version: 2.8.0
```

Wouldn't be more user friendly to output version string on standard output file descriptor?

Replacing `log.Printf` with `fmt.Print` on this [line ](https://github.com/go-task/task/blob/a4685229c96bf695fabb3fb031be7634a3a7f6c2/cmd/task/task.go#L84) should fix output file descriptor.

**Comment by andreynering** [comment]
Hi @lboulard,

Thanks for reporting! Contributions are welcome. 🙂
