### ISSUE TITLE
Please keep packages names consistent for releases

### ISSUE THREAD

**Issue by zbindenren** [go-task/task#30]
Hi

I have automated the rpm creation process of go-task. Changing package name on each release makes this process difficult.

- task_1.3.1_linux_x86.tar.gz (version in package name, x86 instead of x86_64, GOOS lower case)
- task_Linux_x86_64.tar.gz ( no version, GOOS upper case)

Would be great to keep that consistent.

**Comment by andreynering** [comment]
Oops, sorry. It makes sense to make it consistent.

What format do you prefer? It actually make no difference for me.

Also, if you know how to generate RPM and DEB packages, you may want to take a look at https://github.com/go-task/task/issues/15 . I'd love to be able to publish RPM and DEB packages. I think GoReleaser does that together with FPM.

**Comment by andreynering** [comment]
@zbindenren I have setup a fixed name for releases. In future releases it should always be:

- `task_darwin_amd64.tar.gz`
- `task_linux_386.tar.gz`
- `task_linux_amd64.tar.gz`
- `task_windows_386.zip`
- `task_windows_amd64.zip`

**Comment by zbindenren** [comment]
Thx :-)
