### ISSUE TITLE
Command `task --help` ends with an error code of 2 on legitimate invocation

### ISSUE THREAD

**Issue by lboulard** [go-task/task#300]
Running `task-- help` exits with error code 2 because `-help` flag is not defined:
https://github.com/spf13/pflag/blob/2e9d26c8c37aae03e3f9d4e90b7116f5accb7cab/flag.go#L1122

Possible fix:
- Check [pflag error response](https://github.com/go-task/task/blob/347ecc028f994e54576d6f6736aa1b39d496f58c/cmd/task/task.go#L81) and if equals to `pflag.ErrHelp` , do `os.Exit(0)`.
- Add `-help` flag to display usage and do `pflag.Usage(); os.Exit(0)`.

**Comment by andreynering** [comment]
Hi @lboulard,

Thanks for reporting! Contributions are welcome. 🙂
