### ISSUE TITLE
Windows: network paths

### ISSUE THREAD

**Issue by tredoe** [go-task/task#308]
- Task version: master
- OS: windows 10

When I have to use a network path like in the next command:
```
- robocopy "\\VBOXSVR\foo" ".\foo" /e
```
It returns the error:
```
ERROR 3 (0x00000003) Accessing Source Directory C:\VBOXSVR\foo\
The system cannot find the path specified.
```

It seems that it is transforming the prefix '\\' into 'C:\'

**Note:** the command works rightly when it's run in powershell

**Comment by andreynering** [comment]
Hi @tredoe, thanks for reporting this bug!

This sounds like a bug on the shell interpreter library Task uses. I think this use case is uncommon enough that it wasn't noticed before.

I just opened an issue there: https://github.com/mvdan/sh/issues/527.

**Comment by andreynering** [comment]
Hi @tredoe,

Can you try using forward slashes?

```bash
robocopy "//VBOXSVR/foo" "./foo" /e
```

**Comment by tredoe** [comment]
Hi @andreynering,
yes, it works of that way!

Also, the slashes can be used at the beginning (for the network address) and forward slashes for the Windows path.

`robocopy "//VBOXSVR\foo\bar" ".\foo" /e`

Thanks!

**Comment by andreynering** [comment]
Hi @tredoe,

Nice! Closing this issue then...
