### ISSUE TITLE
Invalid option for `read` command in taskfile

### ISSUE THREAD

**Issue by GrzegorzMatuszakTSH** [go-task/task#314]
I'm moving commands from makefile to taskfile.

I have this command in my makefile (works):
```
		read -p "Enter username: " username; \
		sed -i 's/{username}/'$$username'/g' ./file.json; 
```
When I run it using taskfile I get error `read: invalid option "-p"`
```
  test:
    desc: auth
    cmds:
      - |
          read -p "Enter username: " username; \
          sed -i 's/{username}/'$$username'/g' ./file.json; 
```
I tried many options without success.
Is a `read` available in taskfile? 
I'm out of idea how to migrate this command.

**Comment by andreynering** [comment]
Hi @GrzegorzMatuszakTSH, and thanks for opening this issue!

This is currently not implemented on the [shell interpreter library](https://github.com/mvdan/sh) we use. I just opened an issue there to track the progress: https://github.com/mvdan/sh/issues/551.

**Comment by andreynering** [comment]
For now, you should be able to use the `read` command without any flags.

**Comment by GrzegorzMatuszakTSH** [comment]
Thank you for the explanation. As you suggested I changed the script to use `read` without flags and it works :)

**Comment by geek-merlin** [comment]
Also see #420, #421

**Comment by andreynering** [comment]
The support for `-p` was implemented upstream by @parkerduckworth at https://github.com/mvdan/sh/pull/722.

I'm waiting for the new release so we can update the lib here and ship for everyone, but I'll already close this issue so it isn't forgot open.
