### ISSUE TITLE
Add support for delegating CLI arguments with "--" and a special CLI_ARGS variable

### ISSUE THREAD

**Issue by huy-nguyen** [go-task/task#327]
Does go-task currently offer the option of "passthrough" arguments? For example, if I have currently have a task to run the AWS CLI out of a Docker container:
```yaml
tasks:
  aws:
    cmds:
      - docker-compose run --rm aws		
```
Is it possible to have the ability for a command like `task aws -- ls s3://my-bucket` to be translated to `docker-compose run --rm aws ls s3://my-bucket`, meaning `task` will pass through anything after `--` to the underlying shell command? 

This is a more convenient way to pass extra variables compared to the current approach: `task write-file FILE=file.txt "CONTENT=Hello, World!"`. Currently, using this approach allows me to write `task aws CMD="ls s3://my-bucket"` but the extra variable definition and quotes creates a lot of friction that I think can be alleviated with my proposal.

 If this is not possible, it would be a really nice capability to have in the future.

**Comment by andreynering** [comment]
Hi @huy-nguyen, thanks for opening this PR!

This is something that already came up recently by @mbertschler at #316.

Since more people think this would be important, I'll keep this issue open so this could be considered in the future.

I think that what would work is a mixture of these both proposals. We'd both require `--` in the CLI to separate these args from other tasks and flags, and also require a special var to be concatenated in the right task[s]:

```bash
task yarn -- test-ci
```

```yaml
version: '3'

tasks:
  yarn:
    dir: js
    cmds:
      - yarn {{.CLI_ARGS}}
```

**Comment by huy-nguyen** [comment]
@andreynering Your proposal sounds great. The one inconvenience with my current workaround of declaring variables on the command line (`task write-file FILE=file.txt "CONTENT=Hello, World!"`) is that the shell doesn't offer tab completions within quoted strings. Because of that, allowing pass through arguments after `--` is the superior solution.

**Comment by eankeen** [comment]
I am also in strong support of this feature. In my case, I would be appending `{{.CLI_ARGS}}` to most of my commands because I tag on extra arguments ad-hoc pretty frequently. Maybe there could be a way to make enable it as default with some option to reduce duplication?

```yaml
version: '3'

passthroughAllArgs: true

tasks:
	yarn:
...
```

**Comment by stephencheng** [comment]
@huy-nguyen you may want to try it out of: https://github.com/upcmd/up, you can pass through args/vars to a callable task using call func

It is flexible enough, docs here: https://upcmd.netlify.app/call-func/c0020/

**Comment by huy-nguyen** [comment]
@stephencheng upcmd looks very nice and solves a lot of my use cases. How long have you worked it?

**Comment by stephencheng** [comment]
> @stephencheng upcmd looks very nice and solves a lot of my use cases. How long have you worked on it?

@huy-nguyen half year on code base itself, but this is not only about the code, it's about the devpos industry experience I accumulated many years and try to resolve those pain points, all counted, probably a few years :)

**Comment by JulienBreux** [comment]
🆙 Do you have any news about this killer feature?

**Comment by JulienBreux** [comment]
My point of view:

We have this: `task firstTask secondTask`

We went this: `task firstTaks [ARGS]` or `task firstTaks secondTask [ARGS]`.

The question is: how to detect args vs task?

**Comment by JulienBreux** [comment]
@andreynering do you think if we have`passthroughArgs: true` we can cancel the last error and pass arguments to each tasks?

For example: 

1. `task taskExists0 taskExists1 taskNotExists0` with `passthroughArgs: true` = exec taskExists0 with args `taskNotExists0` and exec `taskExists1` with args `taskNotExists0` but no error
2. `task taskExists0 taskExists1 taskNotExists0` without `passthroughArgs: true` = error `taskNotExists0` doesn't exists?

**Comment by andreynering** [comment]
Hi @JulienBreux,

I proposed a solution [in this comment](https://github.com/go-task/task/issues/327#issuecomment-629642649) that I think it'll work well.

**Comment by andreynering** [comment]
This was implemented in e6c4706b73f538e6e29cd78de00c9825f7796b80 and will be available in the next release

**Comment by endorama** [comment]
Hello, I tried using this feature, but I get an error. I tried the proposed YAML config from the configuration, but it's notworking.

Usage:
```
task yarn -- install
task: Available tasks for this project:
* run:          Build and run the web app
* tests:        Run entire testsuite
* tests:single: Run a single test, specify with RUN
task: Task "install" not found
```

`Taskfile.yaml`
```yaml
[...]
tasks:
  yarn:
    cmds:
      - yarn {{.CLI_ARGS}}
[...]
```

To check the behaviour I added a test case to the `args` module (you can look at it [in my fork](https://github.com/go-task/task/compare/master...endorama:master)), but I get an error. It may be because my test case is wrong, but this is the test result, that suggest the parsing for `CLI_ARGS` is not working.

```
    --- FAIL: TestArgsV3/TestArgs8 (0.00s)
        args_test.go:110: 
            	Error Trace:	args_test.go:110
            	Error:      	Not equal: 
            	            	expected: []taskfile.Call{taskfile.Call{Task:"task", Vars:(*taskfile.Vars)(nil)}}
            	            	actual  : []taskfile.Call{taskfile.Call{Task:"task", Vars:(*taskfile.Vars)(nil)}, taskfile.Call{Task:"--", Vars:(*taskfile.Vars)(nil)}, taskfile.Call{Task:"arg", Vars:(*taskfile.Vars)(nil)}}
            	            	
            	            	Diff:
            	            	--- Expected
            	            	+++ Actual
            	            	@@ -1,4 +1,12 @@
            	            	-([]taskfile.Call) (len=1) {
            	            	+([]taskfile.Call) (len=3) {
            	            	  (taskfile.Call) {
            	            	   Task: (string) (len=4) "task",
            	            	+  Vars: (*taskfile.Vars)(<nil>)
            	            	+ },
            	            	+ (taskfile.Call) {
            	            	+  Task: (string) (len=2) "--",
            	            	+  Vars: (*taskfile.Vars)(<nil>)
            	            	+ },
            	            	+ (taskfile.Call) {
            	            	+  Task: (string) (len=3) "arg",
            	            	   Vars: (*taskfile.Vars)(<nil>)
            	Test:       	TestArgsV3/TestArgs8
        args_test.go:112: 
            	Error Trace:	args_test.go:112
            	Error:      	Not equal: 
            	            	expected: &taskfile.Vars{Keys:[]string{"CLI_ARGS"}, Mapping:map[string]taskfile.Var{"CLI_ARGS":taskfile.Var{Static:"arg", Live:interface {}(nil), Sh:"", Dir:""}}}
            	            	actual  : &taskfile.Vars{Keys:[]string(nil), Mapping:map[string]taskfile.Var(nil)}
            	            	
            	            	Diff:
            	            	--- Expected
            	            	+++ Actual
            	            	@@ -1,13 +1,4 @@
            	            	 (*taskfile.Vars)({
            	            	- Keys: ([]string) (len=1) {
            	            	-  (string) (len=8) "CLI_ARGS"
            	            	- },
            	            	- Mapping: (map[string]taskfile.Var) (len=1) {
            	            	-  (string) (len=8) "CLI_ARGS": (taskfile.Var) {
            	            	-   Static: (string) (len=3) "arg",
            	            	-   Live: (interface {}) <nil>,
            	            	-   Sh: (string) "",
            	            	-   Dir: (string) ""
            	            	-  }
            	            	- }
            	            	+ Keys: ([]string) <nil>,
            	            	+ Mapping: (map[string]taskfile.Var) <nil>
            	            	 })
            	Test:       	TestArgsV3/TestArgs8
```

Is this expected? Thanks

**Comment by andreynering** [comment]
Hi @endorama,

Can you confirm you're using the latest release? I have the impression that you may be using an older release.

Also, a test case like you wrote wouldn't work because the variable (for technical reasons) is added on the main package, here:

https://github.com/go-task/task/commit/e6c4706b73f538e6e29cd78de00c9825f7796b80#diff-73fe859c349d50c0779c1c52c76d9c0c736905a058675d37294a447b60e0e693R172

**Comment by endorama** [comment]
> Can you confirm you're using the latest release? I have the impression that you may be using an older release.

@andreynering Sorry for the long wait, but I can confirm this is not happening anymore on `3.4.3`. So everything's good :+1: thank you for the support!

**Comment by xorander00** [comment]
Using a source-build on FreeBSD (13.0) of tags/v3.4.3, -- args aren't being set on CLI_ARGS.  In addition to the below, I also tried quoting it as '{{.CLI_ARGS}}', but to no avail.

I'm not well-versed in Go at all, but not a beginner coder either.  I'm willing to give it a shot later this week to try figuring this out.  Any potential pointers anyone could give me to get started would be much appreciated, thanks! :)

### Taskfile.yml
```yaml
version: '3'

tasks:
  petri0: echo {{.CLI_ARGS}}

  petri1:
    desc: Petri Dish 1
    cmds:
      - echo {{.CLI_ARGS}}
```

### Execution
```sh
$ task petri0
task: echo

$ task petri1
❯ task petri1
task: echo

$ task petri0 -- a b c
task: Available tasks for this project:
* petri1:    Petri Dish 1
task: Task "a" not found

$ task petri1 -- a b c
task: Available tasks for this project:
* petri1:    Petri Dish 1
task: Task "a" not found
```

**Comment by xorander00** [comment]
Tested again.  It's a cross-platform issue between Linux & FreeBSD.  Whether it's due to a compile option on my part or an API/library inconsistency between the two platforms , I'm not sure yet.

**Comment by xorander00** [comment]
Ignore, works with latest.

**Comment by dulataldazharov** [comment]
Is it possible to pass several named or at least indexed CLI arguments?
For example, if I want to pass username and password arguments, and treat them separately.

**Comment by andreynering** [comment]
@dulataldazharov You can pass multiple arguments after `--`, but them all will be joined in the same `CLI_ARGS`:

```bash
task default -- arg1 arg2 'arg number 3'
```

```yaml
cmd: echo {{.CLI_ARGS}}
```

```bash
echo arg1 arg2 'arg number 3'
```

If you need to treat them separately, you need different variables.

**Comment by titpetric** [comment]
@andreynering it doesn't seem to be working with v3@latest (go install): `Task version: v3.20.0 (h1:pTavuhP+AiEpKLzh5I6Lja9Ux7ypYO5QMsEPTbhYEDc=)`;

```
# cat Taskfile.yml | grep CLI_ARGS
      - go build {{.CLI_ARGS}} -tags=goplugin -trimpath .
      - go build {{.CLI_ARGS}} -buildmode=plugin -trimpath -o plugin.so .
```

```
# task -- -buildvcs=false
task: [build-gateway] go build  -tags=goplugin -trimpath .
task: [build-plugin] go build  -buildmode=plugin -trimpath -o plugin.so .
```

Should I file a separate issue for it?

**Comment by titpetric** [comment]
Nevermind, it was on my end - the tasks were invoked with `task name` rather than `task: name`, so CLI_ARGS did not carry

**Comment by stevensgarcia** [comment]
Hi.

Is it possible to isolate a specific argument from .CLI_ARGS? I've been trying this, but I got numbers, I guess the index, but not the value.
(BTW I'm not a golang dev)

```yml
# Task
demo:
    cmds:
      - echo "{{index .CLI_ARGS 0}}"`

# Command
task demo -- arg0 arg1 arg2

# Output
task: [demo] echo "105"
105`
```

Thanks

**Comment by andreynering** [comment]
@stevensgarcia I suggest you to ask for different variable names instead of trying to use `CLI_ARGS` for that. `CLI_ARGS` is meant to keep all arguments on a single string.

**Comment by vaclav-dvorak** [comment]
Hi
this maybe should never been used...

seems go-task is somehow spring complaint (similar to helm) and this hack seem to be working:

```yaml
cmds:
      - echo {{(split " " .CLI_ARGS)._0}}
      - echo {{(split " " .CLI_ARGS)._1}}
```

**Comment by andreynering** [comment]
@vaclav-dvorak Yes, we use [slim-sprig](https://github.com/go-task/slim-sprig), a stripped down version of `sprig` (maintained by ourselves).

Keep in mind that `split` may not work 100% of the time. If you happen to have an argument with spaces inside.

`task default -- foo bar 'foo bar baz'` means `CLI_ARGS` will be `foo bar 'foo bar baz'` and your split would become `["foo", "bar", "'foo", "bar", "baz'"]`.

We might want to add a function `splitArgs` to parse that, which should be relatively simple to implement.
