### ISSUE TITLE
Allow creating arbitrary CLI tools?

### ISSUE THREAD

**Issue by smyrman** [go-task/task#33]
In suggesting #31, I realised that if we allowed `vars` (and optionally a new `args` list) to be specified on the command-line, go-task would basically allow people to _script_ their own arbitrary CLIs with built-in dependency management, without doing much programming to achieve it, and that's actually pretty cool...

- Allowed vars to be specified on the command line using "--param-name" (maybe translated to PARAM_NAME in the Taskfile?)
- If we do add support for "args" for tasks, those could be treated as either named options, or positional arguments.

As of use-cases, there is a lot of computer fields where CLIs are written for internal usage, such as large-scale testing infrastructure and HPC. These CLIs are in my experience thrown-together in some language such as Python, or sometimes even bash, in order to glue together various scripts.

In these cases, creating a CLI is never a goal, but a necessity in order to fit the pieces together. Having an easy way not only to create a CLI, but also to manage dependencies, would be really useful in these fields, although these fields might be slow at changing their tooling.

I am not working in any of those fields now, but I have done so previously.

I am quite happy with this idea being shot down, as I don't think go-tasks original goal at least, was to allow for users to write full-blown CLIs to manage their tasks. I.e. I am sure there are some trade-offs to consider.

**Comment by smyrman** [comment]
As of use-cases, there is a lot of computer fields where CLIs are written for internal usage, such as large-scale testing infrastructure and HPC. These CLIs are in my experience thrown-together in some language such as Python, or sometimes even bash, in order to glue together various scripts.

In these cases, creating a CLI is never a goal, but a necessity in order to fit the pieces together. Having an easy way not only to create a CLI, but also to manage dependencies, would be really useful in these fields, although these fields might be slow at changing their tooling.

I am not working in any of those fields now, but I have done so previously.

**Comment by andreynering** [comment]
I think that would be simple enough, so I think we could add that without any disvantages.

By now, one could use environment variables for that:

```sh
$ VAR1=value VAR2=value task my-task
```

**Comment by smyrman** [comment]
> By now, one could use environment variables for that

Yeah, I realised that as well after writing this. I suppose this is good enough for most of these cases.
Maybe it's best to put this feature on ice to see if there is anyone else that needs or wants it.

>  so I think we could add that without any disvantages.

There is always the one disadvantage of added complexity:-)

**Comment by runeimp** [comment]
When looking at several task runners recently to replace make and be cross-platform the one thing make does that I thought was missing from what is otherwise a very complete feature set was command args. ENV args works but it's not nearly as handy to utilize when rerunning tasks with different values via command history. It's the one thing missing that draws me to other options like myke, and maybe a few others. This discussion makes me very happy with the possibilities!  :-)

**Comment by andreynering** [comment]
@runeimp I'd like to have opinions about what syntax should Task have for this? I don't how Make handle this, will search a bit... 

Maybe this? (`--arg`, alias `-a`) 

```
task my-task -a VAR1=val1 -a VAR2=val2
```

**Comment by runeimp** [comment]
@andreynering That would work for me. I like myke's way as well `myke task1 --key1=val1 task2 --key2=val2 ...`. Would there be any issue just allowing any option with a quote to assumed to be an argument? Something like `task fetch 'host=runeimp.com' port=1969` which is how `make` works to override variables set internally to the `Makefile`. Not sure if that's a Gnu make thing or standard. And maybe just have arguments that fall after a task declaration be scoped to that task only? Something like `task tast1 argname=one task2 argname=two`, etc.

**Comment by andreynering** [comment]
Fixed on master and new release using a syntax similar to bash's environment variables:

```sh
task some-task VAR=foobar
```

**Comment by runeimp** [comment]
Awesome! Can't wait to play with it!  :-D
