### ISSUE TITLE
remove TOML and JSON support?

### ISSUE THREAD

**Issue by andreynering** [go-task/task#34]
Maintaining different formats is getting complicated after #32, specially with TOML, that is a very inflexible format.

[This was asked long ago](https://github.com/go-task/task/pull/3), but I don't think anyone are actually using it.

I'm asking here if anyone have a problem with it first.

/cc @tscholl2 @sascha-andres @smyrman @zbindenren

**Comment by tscholl2** [comment]
I'm not using this, but I think it's great people are still working on it. So if you drop TOML/JSON then it doesn't bother me. Thanks for asking though!

Also I looked at the issue you mentioned. I wasn't sure if this would work, but could you just unmarshal a json file, then marshal it into a yaml string, then unmarshal it using the custom yaml unmarshaler? I might be misunderstanding what's involved though, I didn't read that closely.

**Comment by smyrman** [comment]
I don't have a problem with TOML support, or even JSON, being dropped.

**Comment by sascha-andres** [comment]
I tend to use YAML everywhere as I personally like expressiveness and structure a log. Therefore it would not bother me.

Besides I think supporting one thing right is a better approach as opposed to make it work for everyone ( TOML, JSON and YAML ) with limitations due to the lowest common features.

**Comment by andreynering** [comment]
Thanks for the feedback. I'll drop them soon in the next release, so this don't block us in new features and refactorings.

**Comment by smyrman** [comment]
Just to reply @tscholl2 

> Also I looked at the issue you mentioned. I wasn't sure if this would work, but could you just unmarshal a json file, then marshal it into a yaml string, then unmarshal it using the custom yaml unmarshaler? I might be misunderstanding what's involved though, I didn't read that closely.

You probably could do that, but it's probably somewhat error prone. Another option could be to have an `UnmarshalJSON(data []byte) error` implementation for the type(s) that needs it that does the following:

1. Validates correct JSON, and maybe replace all tabs with two spaces.
2. Calls `UnmarshalYAML(data []byte) error` with the sanitised data.

Most JSON (unless it's indented by tabs) will be considered valid YAML. However, this still leads to having to support two formats.

**Comment by zbindenren** [comment]
I also just use yaml.

**Comment by zbindenren** [comment]
Travis-ci and gitlab-ci only have yaml support. So I think people are quite familiar with it.

**Comment by andreynering** [comment]
Done on master branch

**Comment by carlmjohnson** [comment]
Oh no! I use TOML. Is it too late to switch back? 😢

**Comment by andreynering** [comment]
I'm sorry for that @carlmjohnson 

I know backward incompatible changes are a pain, and I usually thought well before doing them.

Unfortunally TOML and JSON are not as full featured as YAML, and we don't plan to support other formats soon.

You can convert your files to YAML to keep using Task.

**Comment by runeimp** [comment]
@carlmjohnson Checkout [Remarshal](https://github.com/dbohdan/remarshal) to get help you get started on the conversion. I rather like TOML for simple config bit agree that YAML is much better for enhancing `task`.

**Comment by carlmjohnson** [comment]
I ended up converting my TOML to YAML with Remarshall on my own, but thanks for the advice. 😄

**Comment by carlmjohnson** [comment]
BTW, you can see my Taskfile linked in my blog post: https://blog.carlmjohnson.net/post/2017/hugo-asset-pipeline/

**Comment by andreynering** [comment]
@carlmjohnson I saw your article and added it to the [README](https://github.com/go-task/task#task-in-the-wild).

Just more info about why I prefer YAML for Task (in case someone else comes to this issue):

- You can easily write multiline string. In YAML we have the pipe operator `|`, but on JSON you'd have to add uglies `\n`
- You can break big non-multiline string in multiple lines
- TOML in very inflexible, and don't allow much customization in the Go side
- JSON disallow comments
- etc...

**Comment by runeimp** [comment]
@carlmjohnson Yeah, didn't realize your comment was almost two weeks old before I posted.  BTW, nice article!  ;-)
