### ISSUE TITLE
Installation instructions for Nix package manager

### ISSUE THREAD

**Issue by Parasrah** [go-task/task#357]
I've packaged this application for [nix](https://nixos.org/), if that is something that you're interested in advertising on the website. You can check it out [here](https://nixos.org/nixos/packages.html?attr=go-task&channel=nixpkgs-unstable&query=go-task) if so. Also thanks for all the hard work that went into this!

PS: the binary for `nix` has been changed to `go-task` to avoid conflicting with `taskwarrior`

**Comment by andreynering** [comment]
Hi @Parasrah,

Good to know, thanks! ❤️ 

If you want, you're free to open a PR to add a new tab in the "Package Managers" section to this page: https://taskfile.dev/#/installation
