### ISSUE TITLE
Task overriding does not work

### ISSUE THREAD

**Issue by vit1251** [go-task/task#367]
Compile Task from source code in master.
Version output is

```Task version: master```

Documentation provide section about "Operating System specific tasks" but when actually I add Taskfile_{{GOOS}}.yml I does not have override my goals.

I use darwin system.

Do u have debug or more verbose mechanism about use Taskfile is reading. Any additional condition about this mechanism?

**Comment by andreynering** [comment]
Hi @vit1251,

Sorry, this is one piece of the documentation that I forgot to update (I'll use this issue to remember to do that)

This will work that way if you revert your Taskfile to `version: '2'`.

In `v3` this behavior was removed, and you need to manually include that Taskfile:

```yaml
includes:
  foobar: './Taskfile_{{OS}}.yml'
```
