### ISSUE TITLE
Release ARM binaries

### ISSUE THREAD

**Issue by apoorvmote** [go-task/task#375]
I would like to use task with arm processor how to install on arm with deb file?

**Comment by andreynering** [comment]
Hi @apoorvmote,

For now, you need to compile from source to have an ARM binary

It probably makes sense to release binaries for ARM Linux, though. I edited the issue description to reflect that.

**Comment by apoorvmote** [comment]
@andreynering 
Thanks for the reply. I also needed Hugo Extended version for ARM. Hugo contributor showed me how to build from binary. I applied same method for Task and it worked for me. 

But yeah it would be great if you could release ARM binary for linux so I don't have to build it myself.

**Comment by andreynering** [comment]
Starting from the next release, we'll have official ARMv6 and ARM64 binaries

**Comment by apoorvmote** [comment]
Yey!!! Thanks @andreynering
