### ISSUE TITLE
Adding URLs in includes

### ISSUE THREAD

**Issue by tillhoff** [go-task/task#380]
Because I love `task` so much, I use it almost everywhere. While initializing another repo of mine, I recognized that I have lots of redundant tasks in each of those repos.
IMO it would be a great feature to not only allow absolute/relative paths in includes, but also URLs (like https://...).
Like this, I could have a global taskfile for all repos, never copy-paste tasks around and only specify repo-specific tasks.

What do you think about this? It shouldn't impact performance so much, because it's just a tiny peace of text, should it?
Alternatively, do you have a recommendation on how to solve the redundant/multiple-versions-of-the-same-task problem?

**Comment by tillhoff** [comment]
I solved this by adding a Taskfile.yml to the folder containing all downloaded repos and including that into each Taskfile within the repositories.
Just make sure to setup a proper gitignore if you want to version-control this Taskfile.

**Comment by andreynering** [comment]
Hi @tillhoff,

There was some discussions about allowing remote Taskfiles before, but I rejected the idea because it'd bring too much complexity to the codebase.

My recommendation is to do what you did: vendor your included Taskfiles in the repository.

**Comment by tillhoff** [comment]
Thanks for still looking into this :)
