### ISSUE TITLE
Add a `-L` flag (alternative to `-l`) that prints all tasks

### ISSUE THREAD

**Issue by zx8** [go-task/task#383]
Or a new flag should be introduced (e.g. `task --names`) to just output the names of available tasks, with no descriptions.

Currently, a Taskfile with no descriptions returns:

```
$ task -l
task: No tasks with description available
```

While the solution is fairly intuitive (i.e. add a description to every task), the behaviour is surprising. Not to mention it would make the completions much less hacky (for tasks that _do_ have a description):

- https://github.com/go-task/task/blob/ce4ac97269613dc895408722fea2c63cba838f48/completion/fish/task.fish#L2

**Comment by andreynering** [comment]
Hi @zx8,

Perhaps we could add `-L` flag (a an alternative to `-l`) that print all tasks?

Changing the behavior of the existing flag is a backward incompatible change, so not a good idea.

**Comment by zx8** [comment]
Yeah sure, that works!

**Comment by themanifold** [comment]
Slightly different command that does not needs `string`:

```
for i in $(task -l | sed 1d | awk '{print $2}' | awk 'FS=":"{print $1}'); do echo $i; done
```
