### ISSUE TITLE
Could someone give some examples why Task is "simpler and easier to use than GNU Make"?

### ISSUE THREAD

**Issue by orange888** [go-task/task#388]
I appreciate the developers' efforts.

Why is it easier to use Task than Make?
Could you describe some examples?

Thanks.

**Comment by andreynering** [comment]
Hi @orange888,

We have many usage examples in [the documentation](https://taskfile.dev/#/usage). Also, there's this [web app example](https://github.com/go-task/examples/tree/master/go-web-app) if it's what you're looking for.

If you have a more specific question, let me know.
