### ISSUE TITLE
Provide crossplatform way to create ZIP archive with artifact

### ISSUE THREAD

**Issue by vit1251** [go-task/task#391]
Novaday we meet with creating artifact on some platforms with source code and additional files.
Could you please implemnt some ZIP operation for make artifact with compile in single file result files.
I know that I can use commandline but some ugly platform does not provide as default way to compress files.

**Comment by andreynering** [comment]
Hi @vit1251,

I don't think this use case is common enough to implement. I may reconsider it in the future, though (if more people show interest in this).

What I recommend you to do is to create a small Go program that package a directory into ZIP files (maybe someone else already did this). That's a simple way to achieve cross-platform ZIP archiving.
