### ISSUE TITLE
Why is `go get` not supported?

### ISSUE THREAD

**Issue by slimsag** [go-task/task#395]
Hello, first let me say I really like Task and hope to contribute to it and get more adoption of it in my OSS projects (and in my work @sourcegraph where possible.)

One aspect that confuses me a bit is that the installation docs explicitly mention it cannot be installed via `go get`:

> Task requires Go Modules and doesn’t officially support installing via go get anymore.

From what I can tell, nothing about Task prevents `go get` from working and in fact `go get -u github.com/go-task/task/cmd/task` works perfectly fine today - so long as you are running a recent Go version with module support (which I imagine most are at this point.)

I totally understand the binary options being suggested by default, but it's weird to say it doesn't officially support `go get` because it makes me (and I imagine others) think that:

- Task has some very complex build process that doesn't work with `go get`
- Task has some non-idiomatic Go code
- Task requires CGO dependencies that can't be built with `go get`

It seems i haven't been the first with this thought before, as well: https://github.com/go-task/task/issues/250#issuecomment-692723563

My suggestion is to do one of the following:

1. Declare that `go get -u github.com/go-task/task/cmd/task` works - because it does and this is often the preferred installation method of many Gophers.
2. OR at least don't declare that it isn't supported, because this makes me think it doesn't work and gives me a more negative view of Task which does it a disservice. It's a really great tool and I want to see it adopted more :)

**Comment by andreynering** [comment]
Hi @slimsag, thanks for opening this issue!

You're totally right! I think we could change the documentation to tell that `go get` is actually supported.

That was written in the early days of Go Modules, and I think I misunderstood that `go get` actually supports Go Modules.

Contributions are welcome.

**Comment by therealkevinard** [comment]
I think I already have the project local (don't remember for sure if I used go get or git clone && go install). 

The scope here is just removing the "it doesn't work" text? If so, I can do that this afternoon.

**Comment by felladrin** [comment]
I'd like to see it on the documentation too!

I tested and confirm that using:
```
go get github.com/go-task/task/v3/cmd/task
```
Works on Go v1.15 for macOS, Linux, and Windows.

Note the `v3` addition to the module name. I had to add it cause by default it points task/v2, which triggers an error due to incompatibility:

<img width="810" alt="Screenshot 2020-12-06 at 04 16 12" src="https://user-images.githubusercontent.com/418083/101269654-d93a9e00-3779-11eb-8dc0-e9f52d5dde9f.png">

**Comment by andreynering** [comment]
Thanks @slimsag and @felladrin! I just updated the documentation

**Comment by tulis** [comment]
Can we at least put which minimum go version is required in the documentation?

I also found that simply running `go get -u github.com/go-task/task/v3/cmd/task` didn't work.  Instead, I had to run `GO111MODULE=on go get github.com/go-task/task/v3/cmd/task` to make it work. Just to note, I'm on latest version `go1.15.7 linux/amd64`.

**Comment by andreynering** [comment]
Hi @tulis,

I updated the command to have `env GO111MODULE=on` on 8bcd8719aa283fd30d09c0de4b37d2684667b0e0.
