### ISSUE TITLE
How run a service?(daemon)

### ISSUE THREAD

**Issue by jet10000** [go-task/task#413]
How to run a service as a background service

like this

https://github.com/zapty/forever-service

**Comment by andreynering** [comment]
Hi @jet10000,

I don't know exactly what you mean by running as a service, as Task is usually to run stuff once, and not on background (most of the time). You could try using systemd (if you're on Linux).

Probably not what you want, but some people mentioned they used https://github.com/adnanh/webhook to run tasks remotely with a HTTP request.
