### ISSUE TITLE
Document how to make a self-executing taskfile

### ISSUE THREAD

**Issue by geek-merlin** [go-task/task#419]
I found this very handy. Proposing doc snippet:

You can make the taskfile self-executing like this:
- Ensure the task binary is on your `$PATH`
- Add this first line: `#!/usr/bin/env -S task --taskfile`
- Make the Taskfile executable like `chmod a+x Taskfile`
- Optionally rename it

**Comment by andreynering** [comment]
Hi @geek-merlin,

I'm not sure if this is a good practice. Any reason why it's better than calling `task` directly?

I'd prefer not to add this to the official docs, but thanks anyway for opening the issue (someone may find this useful).
