### ISSUE TITLE
Release Checksums

### ISSUE THREAD

**Issue by runeimp** [go-task/task#44]
It would be nice if it was noted somewhere that the values in task_checksums.txt are SHA-256. Maybe inside the text file or in the README.md where it links to the releases page? Could relieve confusion and promote usage.  👼

**Comment by andreynering** [comment]
Hi @runeimp 

I will mention on README. I can't change the content of the file because it's done automagically by [GoReleaser](https://github.com/goreleaser/goreleaser).

Out of curiosity, what are you using these checksums for?
