### ISSUE TITLE
Use arch community repo instead of AUR

### ISSUE THREAD

**Issue by fossdd** [go-task/task#447]
In the [installation intoduction](https://taskfile.dev/#/installation?id=installation) was the AUR image promoted.

Arch Linux provides also the `task` package in the community repo, so it can be easily installed with `pacman -S task`.

**Comment by andreynering** [comment]
Hey @fossdd, thanks for opening this issue!

I don't have an Arch machine, so I can't check it myself. But I have the impression that this `task` package is actually for [Taskwarrior](https://taskwarrior.org/), a different tool which also happen to have `task` as the binary name.

**Comment by fossdd** [comment]
Oh yeah you're right..
