### ISSUE TITLE
Add NO_COLOR env var to disable color output

### ISSUE THREAD

**Issue by danielr1996** [go-task/task#459]
Some people like to have colourless output, for more information see: https://no-color.org/

While I like coloured output it doesn't currently work in windows (#343) so this would also be nice to just disable colour until windows is fixed.

**Comment by andreynering** [comment]
Hi @danielr1996, thanks for the suggestion!

`--color=false` was already supported, but I just added support for `NO_COLOR=1` on  as well.

Ref: https://github.com/fatih/color/pull/137
