### ISSUE TITLE
list all tasks available even if no description is present 

### ISSUE THREAD

**Issue by apatniv** [go-task/task#461]
Currently, I can print a list of tasks if description is present. However, if description is not present, then task seems to emit an warning but don't print the list of tasks.

`
task -l
task: No tasks with description available
`

May be we can have a optional argument to control this behavior.

**Comment by apatniv** [comment]
I would more than happy to do the changes if you think that feature improves usability

**Comment by andreynering** [comment]
There's an open PR which implements this use case: https://github.com/go-task/task/pull/401. I plan to review that soon.
