### ISSUE TITLE
dynamic vars are broken when task has also a dir: attribute

### ISSUE THREAD

**Issue by marco-m** [go-task/task#481]
Hello @andreynering :-)

- Task version: v3.4.2
- Operating System: macOS 11.3

Consider this Taskfile:

```
version: '3'

tasks:
  default:
    dir: x
    cmds:
      - echo hello "{{.FOO}}"
    vars:
      FOO:
        sh: echo impossible
```

If the directory `x` exists, everything is fine:

```
$ mkdir x
$ task
task: [default] echo hello "impossible"
hello impossible
```

But if the directory doesn't exist, Task evaluates the dynamic variable before creating the directory and bugs:

```
$ rm -r x
$ task
task: Command "echo impossible" in taskvars file failed: could not stat: stat /Users/foo/bar/x: no such file or directory
```

and the directory is never created, so also subsequent invocations will fail.

**Comment by ivotron** [comment]
Also happens in Linux. Not sure if this is a bug or a feature. Currently the workaround I implement is to have a dependent task that creates the folder referenced in `dir:`
