### ISSUE TITLE
Have task attempt to fallback to a Taskfile.dist.yml if Taskfile.yml does not exist

### ISSUE THREAD

**Issue by geekygnr** [go-task/task#498]
We want to create a composer project containing tasks of everything that needs to be done for deployments, updates and maintenance.

A standard pattern with projects like this is to have a dist file that can be committed into code and used as a standard configuration until overridden.

An example of this is phpunit.xml.dist is looked for if phpunit.xml does not exist. phpunit.xml.dist would be committed into the repo while phpunit.xml would be a part of the gitignore to allow for environment specific settings.

The request is that task use a similar mechanism and look for a Taskfile.dist.yml when Taskfile.yml isn't present.

**Comment by tylermmorton** [comment]
Hi @geekygnr -- I think this could be achieved with a simple addition of the `.dist` files in `defaultTaskFiles`: https://github.com/go-task/task/blob/master/taskfile/read/taskfile.go#L23

```go
defaultTaskfiles = []string{"Taskfile.yml", "Taskfile.yaml", "Taskfile.dist.yml", "Taskfile.dist.yaml"}
```

In this scenario you would have to include via directory as mentioned here: https://github.com/Lullabot/drainpipe/pull/12#discussion_r644083969

Would like to hear from @andreynering about this but I'd be happy to put up a PR

**Comment by kerma** [comment]
Technically the problem could be solved today with using `Taskfile.yml` and `Taskfile.yaml`. Taskfile.yml is first in the list, so Taskfile.yaml could be used as a default fallback.

**Comment by andreynering** [comment]
I think I like this idea. The implementation should also be simple as @tylermmorton mentioned.

> A standard pattern with projects like this is to have a dist file that can be committed into code and used as a standard configuration until overridden. An example of this is phpunit.xml.dist.

@geekygnr Out of curiosity, do you know other tools that use this pattern other than phpunit?

**Comment by geekygnr** [comment]
I see it most in php tools but that is also where I do most of my development. There are examples of it with phpunit and phpcs that can be seen in drupal core (https://github.com/drupal/drupal/tree/9.4.x/core), it is mentioned in symfony documentation (https://symfony.com/doc/2.2/cookbook/workflow/new_project_git.html).

**Comment by andreynering** [comment]
Just merged as https://github.com/go-task/task/pull/666

**Comment by tylermmorton** [comment]
Awesome! 😈
