### ISSUE TITLE
Output of task help

### ISSUE THREAD

**Issue by runeimp** [go-task/task#51]
On macOS Sierra when I try `task help` I get:

``` text
$ task help
Available tasks for this project:
- default:	Test for Echo
- play:		Run an Ansible Playbook
- wipe:		Terminal screen/buffer wipe
task: Task "help" not found
```
instead of the expected

``` text
$ task help
Available tasks for this project:
default:	Test for Echo
play:		Run an Ansible Playbook
wipe:		Terminal screen/buffer wipe
```

**Comment by andreynering** [comment]
Hi @runeimp 

Sorry, I didn't get it. Are you talking about the below being printed?

```
task: Task "help" not found
```

`task --help` prints Task own help/flags.

Maybe we should add flag `--list` to print commands in current Taskfile?

**Comment by smyrman** [comment]
@runeimp is following the instructions from the README:
 
> Running `task help` lists all tasks with a description. 

Which only really works if there is no task "help" defined in the Taskfile. One or more of --list / --ls / -l sound good to me.

**Comment by andreynering** [comment]
Added `--list` flag and fixed README documentation. Thanks for the report.
