### ISSUE TITLE
Unexpected `dotenv:` overriding

### ISSUE THREAD

**Issue by d3dc** [go-task/task#522]
- Task version: v3.6.0 (h1:RYrzgAOwuyvE6fR3xMaBzQseYKuE7xwQC4SRrpG4TRU=)
- Operating System: alpine 3.14

### Example Taskfile showing the issue

```yaml
version: "3"
dotenv: ['.env', '{{.ENV}}/.env.', '{{.HOME}}/.env']

tasks:
  default:
    - echo $TEST
```

This Taskfile is from the docs on dotenv. One would expect that local configuration would apply over the top of the defaults.

Given an `.ENV` of `development`, I expect `development/.env` to take precedence over `.env`. 

Likewise, any local customizations that I've saved to `~/.env` should apply even if defaults are present.

If I reverse the order of the list, then it will work. I think this is really unintuitive and feels backwards. ~~The author of the documentation made the same mistake~~ it sure feels like a mistake in writing.

Edit: When you compare this to something like [CRA](https://create-react-app.dev/docs/adding-custom-environment-variables#what-other-env-files-can-be-used), they introduce the variables from lowest to highest, but then also describe precedence as left-to-right just a little lower. I imagine this is one that's out in the weeds.

**Comment by kerma** [comment]
I just stumbled upon this as well. I've always expected that the env values are loaded from left to right, and value in the rightmost file will override previously set value. This is not the case however: https://github.com/go-task/task/blob/c79ea5a2576ebc4cfb4e0f605e8d3518eeff0c77/taskfile/read/dotenv.go#L44

Not sure how badly everyone's files break, but it probably cannot be changed anymore. But we'd should explain this in the docs at least..
