### ISSUE TITLE
Verbose Mode Should Report When Task Completes

### ISSUE THREAD

**Issue by ProfessorManhattan** [go-task/task#533]
For the sake of completeness, the Task runner in verbose with (i.e. `task -vvvvv`) should report when a task is complete and starts.

**Comment by SwitchedToGitlab** [comment]
I believe that this should be tagged as a FEATURE REQUEST, as it adds functionality that does not exist currently. I do not believe that this is a "bug" as it does not impede functionality or provide output that the user does not expect. I would agree that for completeness a "task starting" and "task complete" message should be displayed. 

@andreynering thoughts? This should be something simple that even I can make a PR for :)

**Comment by andreynering** [comment]
Hi @ProfessorManhattan and @SwitchedToGitlab,

This is very simple to do. Open to contributions!

**Comment by jespino** [comment]
Submitted a PR for this. I going to give a try to the #532, but looks like I don't have the whole context there to emit the log. I'll take a look.
