### ISSUE TITLE
Add ability to include arbitrary Taskfile/Taskvars files

### ISSUE THREAD

**Issue by moritzheiber** [go-task/task#54]
I'm thinking of the following use-case:

1+n repositories, each of them using a few specialized tasks, while sharing a lot of "common" code. It should be possible for me to include other `Taskfile.yml` and even `Taskvars.yml` files. This makes it easier to share code between runners while staying as flexible as possible.

References could either be files directly, directories or, ideally, HTTP endpoints or even (git) repositories.

**Comment by smyrman** [comment]
I have been thinking about the same (but for files only, and within one repo )...

Example syntax (Taskfile.yml only):
```yaml
include:
  - "subfolder/"
  - "subfolder/Taskfile.yml"
```

It has one issue, and that is that tasks are now on the top-level, so if you add an include or import group, it's slightly counter-intuitive. Also, we would need to consider namespaces to avoid naming collisions.

However, reuse of task in other Taskfiles are allready possible today. you could rely on calling taskvia cmds:
```yaml
subtask:
  dir: subdir
  cmds:
    - task subtask
  status:
    - task subtask-status
```

You loose the up-to-date that you would get resolutions, but as shown, that can be accessed by implementing a custom status check.

**Comment by smyrman** [comment]
I vote for closing this in favour of #98, which has a very clear description.

**Comment by moritzheiber** [comment]
I agree, thank you!
