### ISSUE TITLE
Allow Access to Main Shell Context for Interactive Scripts

### ISSUE THREAD

**Issue by ProfessorManhattan** [go-task/task#540]
I am interested in learning whether or not it is possible to run an interactive shell script initiated by Task. I have various scripts including `lint-staged`, custom prompts, and other libraries that I would like to be given access to the same context that Task is running it. Node.js npm scripts does this.

For example, if you provide Task with the following it does not prompt the user for input:

```
read example
```

I would like to open the PR for this but I'm not sure where to start because I have never written in Go before. Is this something we can already accomplish? Can anyone provide me with some details of how to implement this?

**Comment by ProfessorManhattan** [comment]
I was facing this issue because I was using `output: prefixed` and do interactive stuff as well?

**Comment by andreynering** [comment]
Hi @ProfessorManhattan,

Sorry, but `output: prefixed` and interactive scripts together is not supported.
