### ISSUE TITLE
What Version?

### ISSUE THREAD

**Issue by runeimp** [go-task/task#55]
I have no idea what version of Task I have installed. Just that it was probably from the master branch. An example of running `task --version` on my macOS Sierra system.

``` bash
$ task --version
Task version: master
```

**Comment by zbindenren** [comment]
You probably installed it with go get, thats master. If you want version info, install a release.

**Comment by andreynering** [comment]
@zbindenren is correct.

`go get` builds can't be customized, so `master` is the default value.

For releases, GoReleaser sets the appropriate version in the version variable.

**Comment by andreynering** [comment]
If you use `task install`, version will be the current commit:

https://github.com/go-task/task/blob/dc6cb68327064b1ef70bee81efcc69ee48be6dd9/Taskfile.yml#L6
