### ISSUE TITLE
Document description error about fromSlash 

### ISSUE THREAD

**Issue by agstar** [go-task/task#555]
- Task version: 3.0
- Operating System:

The description of `fromslash ` in the Go's template engine section is wrong.

`fromSlash` is described as the same as `toSlash`.

![image](https://user-images.githubusercontent.com/34125584/129910459-f3fa4216-e628-46f5-8ce2-167a2e66b256.png)

**Comment by andreynering** [comment]
Fixed, thanks for reporting @agstar!
