### ISSUE TITLE
Docs reference the deprecated "expansion" keyword

### ISSUE THREAD

**Issue by binyamin** [go-task/task#575]
The website references "expansion" keyword, which is deprecated as of version 3 ([source](https://taskfile.dev/#/taskfile_versions?id=version-3))

**Known sections**
- https://taskfile.dev/#/styleguide?id=use-the-correct-order-of-keywords
- https://taskfile.dev/#/styleguide?id=separate-with-spaces-the-mains-sections

**Comment by andreynering** [comment]
Thanks, fixed.
