### ISSUE TITLE
parse Taskfile.yaml files

### ISSUE THREAD

**Issue by mikekantzer-drizly** [go-task/task#584]
Per the [yaml.org FAQ](https://yaml.org/faq.html):
> Please use ".yaml" when possible.

The last PR I saw about this was several years ago, but I think it's worth a new discussion.

**Comment by dirien** [comment]
Hi @mikekantzer-drizly,

I am complety agree on this! I would suggest a similar approach, like @caarlos0 did on goreleaser -> 

https://github.com/goreleaser/goreleaser/blob/df0216d5855e9283d2106fb5acdb0e7b528a56e8/cmd/config.go#L15-L18

I checked the code, and it should be quick to add `yaml` as additional ending, without breaking any existing files.

**Comment by iangregsondev** [comment]
This would be a great feature, my internal naming convention for yml files is actual yaml, so it would be nice if taskfile looked for both yml and yaml file.

**Comment by dirien** [comment]
Thanks to @kerma, for creating the PR!
