### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by ProfessorManhattan** [go-task/task#596]
Is there a roadmap for upcoming features? It seems like development has paused so I'm just curious

**Comment by andreynering** [comment]
Hi @ProfessorManhattan,

Regarding the slow development see #610.

I don't have a strict guideline, but Docker integration would be interesting but also time demanding, so do not expected that too soon.

---

Other than that I'd like to ask a bit more collaboration on your part. I see you opened many issues recently. Some are duplicated with each other (#543, #602, #605). Some are duplicated with existing issues from other users (#606, #607).

Could you please close the duplicates and keep issues at a minimum? Don't take it personally, it's just a tip to help us being more efficient. Valid issues are still more than welcome. Thanks! 🙂

**Comment by ProfessorManhattan** [comment]
Hey @andreynering -- I'm more than willing to collaborate. I linked to a fork in several issues that has a bunch of new features but the issues were just closed without any comments about whether or not you wanted PRs for the features.
