### ISSUE TITLE
cgo doesn't work on windows after upgrade to 3.9.1

### ISSUE THREAD

**Issue by glumia** [go-task/task#619]
- Task version: 3.9.1
- Operating System: windows

Additional requirements:
- go
- gcc

Minimal project to reproduce the issue:
```
.
├── greeting.h
├── main.go
└── Taskfile.yml
```

greeting.h:
```C
#include <stdio.h>

void greeting() {
   printf("Hello, World!");
}
```

main.go:
```go
package main

// #cgo CFLAGS: -g
// #include "greeting.h"
import (
	"C"
)

func main() {
	C.greeting()
}
```

Taskfile.yml:
```yml
version: '3'

tasks:
  greeting:
    cmds:
      - go run main.go
```

`task greeting` works perfectly fine with version 3.9.0 but fails on 3.9.1 with the following message:
```
task: [greeting] go run main.go
# command-line-arguments
cgo: C compiler "gcc" not found: exec: "gcc": executable file not found in %PATH%
task: Failed to run task "greeting": exit status 2
```

---

Related to https://github.com/arduino/arduino-cli/pull/1576.

**Comment by andreynering** [comment]
Hi @glumia,

I reported this upstream at https://github.com/mvdan/sh/issues/768.

**Comment by andreynering** [comment]
A new release with the fix was just published: https://github.com/go-task/task/releases/tag/v3.9.2
