### ISSUE TITLE
task as pipeline infrastructure

### ISSUE THREAD

**Issue by mike-dubman** [go-task/task#625]
use-case: 
* use taskfile as pipeline engine to call from any CI engine  (jenkins, gitlabci,...) as CI agnostic pipeline definition and make it portable.
* bonus: users can run pipeline tasks from shell cli as well

gaps comparing to "make replacement" use-case:

1. ability to run all tasks "in-order of appearance in the taskfile" and do not require "default/all task with ordered list of tasks".
Example: task -t pipeline.yaml -run-all

2. ability to print (without execution) resolved pipeline flow (as yaml) file, so CI engine can transform it into visual entities (steps)

Example: task -f pipeline.yaml -run-all   -show-all-flows 

pipeline1:
  task1
  task3
  task4

pipeline2:
  task2
  task5
  task6

3. ability to run selected pipeline, step-by-step

Example: 
   task -t pipeline.yaml -flow pipeline1 -step 1
   task -t pipeline.yaml -flow pipeline1 -step 2
   task -t pipeline.yaml -flow pipeline2 -step $i++

Please advise

**Comment by andreynering** [comment]
Hi @mike-dubman, and thanks for opening this issue.

This seems like a too broad feature request, and a bit out of the scope of this tool IMO.

You can still run Task from within your CI, but you need to structure your Taskfile in a way that allows you to call the right task from each pipeline from Jenkins (or other), for example.

**Comment by mike-dubman** [comment]
> Hi @mike-dubman, and thanks for opening this issue.
> 
> This seems like a too broad feature request, and a bit out of the scope of this tool IMO.
> 
> You can still run Task from within your CI, but you need to structure your Taskfile in a way that allows you to call the right task from each pipeline from Jenkins (or other), for example.

thanks for your reply and comments.

calling individual task from CI disables automatic dependency resolving if task depends of chain of others.
it beats the purpose.
