### ISSUE TITLE
Timestamps Needed

### ISSUE THREAD

**Issue by ProfessorManhattan** [go-task/task#629]
It is currently somewhat difficult to pinpoint exactly where bottlenecks are in a flow. Can you please add timestamps that output the number of ms a task takes?

If we implement this feature, the timestamps should record the total time including vars/env since those can contain shell scripts. The timestamps should also show up next to the "is up to date" messages.

Thank you so much for this project! I love it

**Comment by kerma** [comment]
Hey @ProfessorManhattan! To me it sounds like you're better served by something like unix `time` command. It'll give you the flexibility to decide where and when you need to measure the time taken to run a dynamic variable or a command.

However, adding a total run time for the executed task in verbose mode would make sense and doesn't require a major change.

**Comment by tylermmorton** [comment]
Closing as a duplicate of #551
