### ISSUE TITLE
Remove deprecated "$" and "^" prefixes

### ISSUE THREAD

**Issue by andreynering** [go-task/task#644]
`$` is a variable prefix that make it being evaluated as shell. It was replaced with `sh:`.

`^` is a command prefix that make it run another task. It was replaced with `task:`.

These were added long ago when we were experimenting with stuff and kept for some time for backward compatibility reasons, but sometimes causes confusion and I think the time to remove the code came.

**Comment by Trite8Q1** [comment]
Hi,
I'd like to take that

**Comment by andreynering** [comment]
Nice! This should be an easy one. There may be one test or another to be deleted in the process.

**Comment by Trite8Q1** [comment]
Thanks for your answer! 
This will help me to learn Go and build a portfolio for open source projects.
So this 'refactoring' (?) should be done in the whole project or only in a specific scope?

**Comment by andreynering** [comment]
It's basically a matter of removing these conditions:

https://github.com/go-task/task/blob/d5d198411625c638084326dd3a4d21504e9e44fb/taskfile/cmd.go#L26-L28

https://github.com/go-task/task/blob/d5d198411625c638084326dd3a4d21504e9e44fb/taskfile/var.go#L111-L113

**Comment by Trite8Q1** [comment]
Is the change correct, or should I change something? If it's correct, I'll create a PR.

**Comment by andreynering** [comment]
@Trite8Q1 It just misses the `return nil` statement on both cases.

Feel free to create the PR. Then we can see if the tests pass and do another review.

**Comment by Trite8Q1** [comment]
All right. I've updated it and created a PR.  👍🏽 :)
