### ISSUE TITLE
-s (silent) not respected, use stderr for task output

### ISSUE THREAD

**Issue by smyrman** [go-task/task#68]
When running a task with `-s`, I would expect it to be silent about non-command output. Instead, I see the output:

`task: Task "bin/my-binary" is up to date`

This is for a simple task with one dependency with status checks.

What is worse, is that this output is printed to stdout, not stderr which makes it it hard to pipe stdout output from the executed `cmds` _only_ into a variable:

```
$ MY_VAR=$(task -s my-task)
```

I would suggest the following:
- Information about up-to-date tasks is not printed when -s is specified.
- All information not coming from executed shell commands is printed to stderr rather than stdout. That makes it easier to distinguish command output from task logs.

(btw, it's more common to use -q / --quiet than -s / --silent).

**Comment by andreynering** [comment]
> Information about up-to-date tasks is not printed when -s is specified.

I'm fine with the above.

> All information not coming from executed shell commands is printed to stderr rather than stdout. That makes it easier to distinguish command output from task logs.

I don't have any strong feeling for this one. `task: Task "bin/my-binary" is up to date` is not an error to be written to `stderr`, but I think it's fine to change that. Do you know if other programs often use this convention?

**Comment by smyrman** [comment]
> Seems stderr should also be used for these kind of messages,

Indeed. E.g. if you run `curl -L https://example.com > filte.txt`, the content from the URL will be written to stdout, and any log messages such as a download progress par would be printed to stderr. Most commands work in a similar manner.

**Comment by zbindenren** [comment]
Sounds good

**Comment by smyrman** [comment]
thanks @andreynering 👍
