### ISSUE TITLE
Installable with Chocolatey for Windows users

### ISSUE THREAD

**Issue by vicmattos** [go-task/task#683]
Hey all,

I just got to know this tool and I'm really looking forward to integrate it in the projects that I work on.

A lot of my Windows fellows use [chocolatey](https://chocolatey.org/) as their package manager in windows, and it would be easier to sell this introduction to them if they could keep their standard tools.

I read the [documentation about it](https://docs.chocolatey.org/en-us/create/) and doesn't seem too complicated.

**Comment by andreynering** [comment]
Apparently @Starz0r have been publishing new releases already: https://community.chocolatey.org/packages/go-task

**Comment by vicmattos** [comment]
Amazing!! Only adding this installation alternative in the documentation site missing.

**Comment by andreynering** [comment]
Certainly

**Comment by vicmattos** [comment]
Sorry for the delay.

Since I didn't find a CONTRIBUTING I did as I assumed getting references from other PR's.

@andreynering, I have an option to merge. Should I?

**Comment by andreynering** [comment]
Hi @vicmattos,

No need to be sorry, at all! 🙂 

Seems that you opened that PR against your own fork. You should open another one targeting this repository instead, them I could merge it.

In the meantime, I did two comments there.

**Comment by vicmattos** [comment]
Hi @andreynering,

Ops, sorry for that. Created the PR in the right repo now.

And thanks for your review!!
