### ISSUE TITLE
HTTP Interface

### ISSUE THREAD

**Issue by ZUNbado** [go-task/task#69]
I would like to have a small web server that would allow me to execute the tasks remotely.

For example, sending a request to http: //host:8888/taskname would execute the task "taskname"

Like this basic example of dog: https://github.com/dogtools/dog/blob/master/examples/http-api/http-api.go

It would be interesting if the access was limited by a token / user

**Comment by andreynering** [comment]
Interesting use case. I didn't know similar tool had something like this.

I think this should be a separated project instead. It should be trivial to call the `task` executable with parameters + tags.

If someone decide to implement it, I could create a repo in [the organization][org] for it.

[org]: https://github.com/go-task

**Comment by zbindenren** [comment]
I agree

**Comment by ZUNbado** [comment]
Hi, i found a similar solution https://github.com/adnanh/webhook

**Comment by andreynering** [comment]
This is a very old issue, and I think this feature is a bit out of scope for this tool

The linked [webhook](https://github.com/adnanh/webhook) is probably a better fit for this use case
