### ISSUE TITLE
Add template function to return the Taskfile directory

### ISSUE THREAD

**Issue by robinbryce** [go-task/task#72]
Hi,

I'm trying to do a moderately fiddly env: VAR construct. At a minimum, I'd need the directory containing the taskfile as a variable. The following doesn't seem to work (and isn't ideal anyway)
~~~
mytask:
  env:
    CGO_LDFLAGS: '-I$(pwd)some/path'
~~~
The contents of the string are not shell evaluated as far as I can tell (that is probably a good thing!)

I think {{.TASKFILEDIR}} would be ideal. 

An alternative I looked into was calling `{{ .os.Getwd }}` but that doesn't seem to work (I think it would have to be added by task to the global functions before evaluating the task file) and in any case, just like pwd, would make my task definition dependent on the current working directory.

Can you suggest a good way to achieve the result I'm after ?

**Comment by robinbryce** [comment]
Hmm, ok I think maybe

TASKFILEDIR=where/ever task

And set TASKFILEDIR to the empty string in Taskvars.yml will be good enough here. If that is the answer please just close this.

**Comment by andreynering** [comment]
In most cases you don't need absolute path, relative path would work (but this depends on the tool you're calling).

But I don't mind adding a func to return the dir. Changed the issue title to reflect that.

**Comment by smyrman** [comment]
Should it return the `Taskfile` directory, or the `task` directory? Maybe the absolute `task` directory would be more useful?

**Comment by andreynering** [comment]
@smyrman Hmm... good point

**Comment by robinbryce** [comment]
I think both would find use cases. Directory of task would be "my current context", Directory of Taskfile would be "top of my project" and likely useful for referring to things shared between tasks. In my particular case I can work with either.  Maybe implement one and see if there are any unintended consequences ?

I think this is something like "abs_top_srcdir" and friends from autoconf. Note: I am not advocating emulation of autoconf!

https://www.gnu.org/software/autoconf/manual/autoconf-2.61/html_node/Preset-Output-Variables.html

**Comment by smyrman** [comment]
This appear to work for us for finding the directory of a task-file:
```yaml
version: "2.1"

vars:
  TARGET_DIR:
    sh: pwd

tasks:
  echo-path:
    cmds:
    - "echo '{{.TARGET_DIR}}'"

**Comment by smyrman** [comment]
If nothing else, it may solve as a work-around.

**Comment by andreynering** [comment]
@smyrman Yep, I think that works well enough

I decided to close this, but if someone don't think that's enough, feel free to comment

**Comment by lcg635** [comment]
If a task file is included by some other task file, current directory of tasks is not the directory of first task file.
@andreynering

**Comment by andreynering** [comment]
@lcg635 Yeah, there was discussion about it. It currently works as you described, but I knew this request would come up any time.

I opened another issue for it: #144
