### ISSUE TITLE
watch: run command for each changed file

### ISSUE THREAD

**Issue by sl5net** [go-task/task#73]
hi :) may tell me how i get the filePath for each changed file?

BTW this is not really working. {{FILENAME}} prints <no value>

// task assets build -w

build:
  cmds:
    - go build -v -i main.go

assets:
  cmds:
    - echo "{{FILENAME}}"
  sources:
    - src/css/**/*.css

**Comment by andreynering** [comment]
This is not currently implemented. Related: https://github.com/go-task/task/issues/29

**Comment by andreynering** [comment]
Closing this in favor of https://github.com/go-task/task/issues/82
