### ISSUE TITLE
Add winget to the list of managed package managers

### ISSUE THREAD

**Issue by Geims83** [go-task/task#736]
As winget is bundled in the latest versions of Win 10 & 11, it would be nice if it was supported.

**Comment by andreynering** [comment]
As I haven't been using Windows often recently, so I don't plan to work on this soon.

That said, if anyone has instructions on how to proceed to do that, or perhaps even want to contribute with this, please let me know.

**Comment by gedw99** [comment]
Hee is a golang program using it

https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/.github/workflows/winget.yml

The config for it: https://github.com/JanDeDobbeleer/oh-my-posh/tree/main/packages/winget

**Comment by sanzoghenzo** [comment]
+1 on this!

There's also a [GitHub Action](https://github.com/marketplace/actions/winget-releaser) to make things easier; the only small issue is that it needs one version of the app already on the repository, so the first upload has to be done manually.

**Comment by gedw99** [comment]
https://github.com/vedantmgoyal2009/winget-manifests-manager.
https://github.com/vedantmgoyal2009/winget-releaser

These do it for you.

**Comment by dpprdan** [comment]
goreleaser recently gained [winget support](https://goreleaser.com/customization/winget/#winget)

see [chezmoi](https://github.com/twpayne/chezmoi/blob/master/.goreleaser.yaml#L248-L282) for an implementation

**Comment by andreynering** [comment]
This was already done, just this issue forgotten open.

See:

- https://taskfile.dev/installation/#winget
- https://github.com/go-task/task/pull/1090
- https://github.com/microsoft/winget-pkgs/tree/master/manifests/t/Task/Task

**Comment by dpprdan** [comment]
AFAIU task is indeed on winget, but new releases do not get added to the winget-pkgs repo automatically. Or have I missed something? 

The latter, i.e. goreleaser submitting updated manifests for new releases to the winget-pkgs repo, is what my comment above was about.

**Comment by andreynering** [comment]
I thought people on Microsoft would deal with new releases, but it seems I'm wrong. We didn't implement this support, they did.

But given Goreleaser in theory supports opening a PR automatically, I'll take a look at setting that up.

**Comment by eitsupi** [comment]
As a quick note, I opened a new PR using Komac[^1] (microsoft/winget-pkgs#113284).

Whether GoReleaser or Komac, it would be great if this could be automated on existing workflows.

[^1]: <https://github.com/russellbanks/Komac>

**Comment by dpprdan** [comment]
> I thought people on Microsoft would deal with new releases, but it seems I'm wrong. We didn't implement this support, they did.

AFAICT only (surprisingly) few winget manifests get submitted to the repo by Microsoft employees, most is done by "the community". I, for one, submitted manifests for programs that I wanted to be able to manage with winget. The [manifests for Task](https://github.com/microsoft/winget-pkgs/tree/master/manifests/t/Task/Task) were not submitted by Microsoft either (again AFAICT).

**Comment by Geims83** [comment]
Is anybody having issues with the installation from winget?
I'm not seeing any release after the 3.28 one.
