### ISSUE TITLE
Install script not found

### ISSUE THREAD

**Issue by vinicius73** [go-task/task#746]
The installation script https://taskfile.dev/install.sh is offline.

![image](https://user-images.githubusercontent.com/1561347/170886544-462d514d-ef7c-407d-9271-39bfee1fa848.png)

**Comment by vinicius73** [comment]
As alternative I am useing 
https://raw.githubusercontent.com/go-task/task/master/install-task.sh

**Comment by andreynering** [comment]
Hi @vinicius73,

Thanks for reporting it! This was a mistake and I just fixed it.
