### ISSUE TITLE
Have versioned Taskfiles

### ISSUE THREAD

**Issue by andreynering** [go-task/task#77]
Something like this:

```yml
# Taskfile.yml
version: 2

# ...
```

Easier said than done, though. Ideas on implementation welcome.

/cc @smyrman  @zbindenren

**Comment by smyrman** [comment]
I think the easiest implementation is to do two passes of the file's content.

1. The first pass you parse possibly only the first line, and look for a `version: "2"` (using string as that allows "2.3.4" etc.). If it's not found, assume version `"1"`.
2. Second pass, do a switch-case on the version, and use either package `taskfile/v1` or `taskfile/v2` to parse the entire yaml file content and handle some of the logic.

If possible, the v1 and v2 packages should implement a common, minimalistic interface.

At a more fine grained level, while selecting `v2`, `v2.1` features should preferably be disabled, but this can be pushed until the relase of `v2.1`, which I assume is still quite some time in the future. For a format that is not yet stable, it could be made available with `version: experimental` or so, including no backwards guarantees.

Whatever the implementation, the most critical part, is that

**Comment by andreynering** [comment]
Implemented as part of https://github.com/go-task/task/pull/93

Currently the version is a simple int, not a semver string like `v1.2.3`. Before v2 release, we can still discuss change this, if you think it would be better.

**Comment by smyrman** [comment]
It would be better to use a string over an int to allow _integrity_ of the version string. E.g, use "2alpha1" before the "2.0" release, and prevent "2.1" directives from having an effect in "2.0" documents. That way people's version of `task` should not affect how the `Taskfile` is interpreted (except for bugs being fixed of course). 

It's probably a bit harder to set-up and test though, so given the size of the project, an `integer` is probably OK, one just need to be aware of the trade-off.

**Comment by andreynering** [comment]
@smyrman I think I'll keep it as a simple int for simplicity of implementation. This seems also what others tools use (Docker compose, etc).

(Maybe I can add an exception and allowing something like `experimental`, though).

Yes, I plan to increments the version when having any *breaking* change (not all changes, like new features that don't break existing Taskfiles).

Something I'm not sure is if Task versions should follow Taskfiles versions. E.g. should Taskfile `version: 3` require the release of Task `v3.0.0`?

**Comment by atar-axis** [comment]
@andreynering absolutely, would be super confusing otherwise.

**Comment by smyrman** [comment]
> This seems also what others tools use (Docker compose, etc).

That is not true, they use a string, e.g.  `version: "3"` , `version "3.1" etc`. If writing `"3"`, `"3.1"` features are not available. That said, docker-compose has a large engineering team to maintain this form of compatibility.

> Something I'm not sure is if Task versions should follow Taskfiles versions. E.g. should Taskfile version: 3 require the release of Task v3.0.0?

I don't think that's important, but it should be documented. depends if the CLI / lib should use semvers --  it may make sense to make a new CLI/lib v3, without releasing a new format for the Taskfiles.

**Comment by andreynering** [comment]
@smyrman OK, thinking better, let's use semver then, since there's a couple of semver libs out there to make it easier:

- [blang/zemver](https://github.com/blang/semver)
- [Masterminds/semver](https://github.com/Masterminds/semver)
- [coreos/go-semver](https://github.com/coreos/go-semver)
- [ryanuber/go-semver](https://github.com/ryanuber/go-semver)

Let's make it future-proof from the start, to prevent any regrets.

@atar-axis OK, Taskfile versions following Task versions would be easier to users to understand.
