### ISSUE TITLE
fedora: install documentation for go-task is misleading

### ISSUE THREAD

**Issue by ssbarnea** [go-task/task#774]
https://taskfile.dev/installation/#fedora page states that you can use dnf to install go-task but that is not true, at least not for current version (36) of Fedora.

Should I make a PR to remove the entire section?

One funny remark is that I observed that go-task would conflict with taskwarrior as both use the same command line `task`. I wonder if that could be the reason why it was not added to Fedora.

I used taskwarrior long time ago but I have no idea if the project is still widely used.

**Comment by andreynering** [comment]
Hi @ssbarnea,

That was added very recently by @mefuller on #767. I do not use Fedora, so I can't really test it to check if it works.

Can you both @mefuller and @ssbarnea discuss and make a conclusion about what to do with that section?

Ubuntu has `apt-get update` to update the package database about new packages/versions, etc. Maybe something similar was missing for @ssbarnea to be able to install it?

**Comment by mefuller** [comment]
Hi @ssbarnea ,

If you follow the link in the installation section to https://packages.fedoraproject.org/pkgs/golang-github-task/go-task/ you will see that the package is currently built and in the stable repository for rawhide.

It will be built and pushed to testing on F35 and F36 within a week (hopefully) and should go stable a week after that.

Sorry for the confusion

**Comment by mefuller** [comment]
@andreynering @ssbarnea can we close this out?
`go-task` is in stable across all current Fedora releases: https://src.fedoraproject.org/rpms/golang-github-task
