### ISSUE TITLE
Hability to easily download and install a specific Task version

### ISSUE THREAD

**Issue by andreynering** [go-task/task#78]
I thought about using a custom domain for import path (e.g. `go get taskdomain.com/v1.4.3`), but Go don't support specifying tags or branches.

Maybe a bash script that downloads and installs from GitHub releases?

Who use Ubuntu can already use the Snap package.

Ideas?

**Comment by smyrman** [comment]
Sh scripts could be one way, but there will always be at least some challenge to make it work cross-platform, at least between Mac and various Linux distros, not to mention Windows.

If switching to semantic versioning, using http://labix.org/gopkg.in could make sense. That only allows specifying `v1` or `v2` when downloading (go get), but if semantic versioning is followed, that should be enough.

This means two things for developement:
- Every-time there is a breaking change (public API change, commandline change, drop format support), The MAJOR number in MAJOR.MINOR.PATCH _must_ be increase.
- Either you do major releases often, don't do breaking changes, or have a master branch that will only release, say once a year with tons of breaking changes. I am not going to recommend any particular strategy.

A third option is to wait for some tool (e.g. `dep`) to allow it, or even be included in the Go standard library. I assume it will happen eventually, it's just a question about time.

**Comment by andreynering** [comment]
I think this will do the trick: https://github.com/goreleaser/godownloader

**Comment by smyrman** [comment]
looks like it. However, since you now gotboth snap, homebrew and binary, maybe thats good enogh for now.


Perhaps would vgo eventually aloww this? I am OK with closong this.
