### ISSUE TITLE
Docs are not correct sources and status can co-exist

### ISSUE THREAD

**Issue by ghostsquad** [go-task/task#788]
Docs indicate that status overrides/precedes sources. But #477 says otherwise.

https://taskfile.dev/changelog/#v360---2021-07-10

**Comment by andreynering** [comment]
Hi @ghostsquad,

They can coexist. Look at this code:

https://github.com/go-task/task/blob/e36c77aaf3ed88be1583868288958bb272534fa0/status.go#L31-L61

If both checks are available, both need to pass for the task to be run.

If you think something is not working correctly, can you attach an example Taskfile that shows the issue?

**Comment by ghostsquad** [comment]
@andreynering I'm pointing out that the docs don't reflect that these can co-exist. The docs need to be updated

**Comment by andreynering** [comment]
@ghostsquad Can you submit a PR?
