### ISSUE TITLE
Semver strings in `version` field are not supported

### ISSUE THREAD

**Issue by xTVaser** [go-task/task#796]
- Task version: `3.13.0`
- Operating System: Windows

### Example Taskfile showing the issue

```yaml
version: "3.13.0"

tasks:
  test: "echo hello world"
```

The documentation states that a semver string is accepted - https://taskfile.dev/taskfile-versions/#what-the-taskfile-version-mean and it seems that previous issues tried to future proof this https://github.com/go-task/task/issues/77 but it doesn't seem to be functioning as expected.

With the yaml above:
> PS C:\Users\xtvas\Repositories\opengoal\jak-project> task test
task: Could not parse taskfile version "3.13.0": strconv.ParseFloat: parsing "3.13.0": invalid syntax

It seems to be parsed as a single float, not a semver string - https://github.com/go-task/task/blob/d8555e5a5ded8230b203a995d9b0bd7e62316cfd/taskfile/taskfile.go#L65-L71

So `"3.13"` works given that
> PS C:\Users\xtvas\Repositories\opengoal\jak-project> task test
task: [test] echo hello world
hello world

As an aside, is the version only checked against features?  It would be nice to be able to enforce a given minimum version to ensure a user has necessary bug fixes.  Currently I don't think this is the case -- if I set it to a nonexistent version like `3.14`, there is no error.

**Comment by vmaerten** [comment]
This is working since v3.22.0
