### ISSUE TITLE
Cannot execute some shell builtin commands like "hash -r" or "command -V"

### ISSUE THREAD

**Issue by mrkeuz** [go-task/task#804]
Cannot execute some shell builtin commands like "hash -r" or "command -V"  inside task.

Some scripts, like i.e. python `virtualenv` activate using these commands for correct propagate new PATH variable. So when you try `source {venv}/bin/activate` it fails on exactly on these command.

In other hand many other builtin commands works as expected: `echo`, `type`, etc.

```shell
$ type hash   
hash is a shell builtin
$  type command
command is a shell builtin
$ type echo
echo is a shell builtin
$ type type
type is a shell builtin
```

- Task version: Task version: v3.14.0 (h1:/00rpwoB+lo9ztU7MPa9aCDywZvrXaxXNR2BxvyEhwE=)
- Operating System: Ubuntu 20.04 + bash/zsh

### Example Taskfile showing the issue

```yaml
version: '3'

tasks:
  default:
    cmds:
      - hash -r
      - command -V ls
```
Output:
```console
task: [default] source test.sh
task: [default] hash -r
"hash": executable file not found in $PATH
task: Failed to run task "default": exit status 127
```

**Comment by ghostsquad** [comment]
each `cmd` is a separate shell. Sourcing a file in one does not carry over to the next.

**Comment by ghostsquad** [comment]
For the remaining built-ins. Please file an issue with https://github.com/mvdan/sh
