### ISSUE TITLE
task does not follow directory symlinks when checking for dependencies

### ISSUE THREAD

**Issue by mbergal** [go-task/task#826]
- Task version:  v3.14.0
- Operating System: Ubuntu 20.04

### Example Taskfile showing the issue

See https://github.com/mbergal/task-symlinks-example

```
> task 
...
> echo aaa > src/a
...
> task
> echo aaa > src/shared/b
task: Task "default" is up to date
```

**Comment by andreynering** [comment]
Hi @mbergal, thanks for reporting!

If anyone is interested, contribution is welcome with this one.

**Comment by ilewin** [comment]
I'd like to give it a try.
There is a similar issue in mvdan.cc/sh (shell interpreter used in task)
https://github.com/mvdan/sh/issues/843
