### ISSUE TITLE
Make "--list" and "--list-all" output colored

### ISSUE THREAD

**Issue by orenmazor** [go-task/task#845]
I'd like my taskfiles to be used as their own manpages.

So I could have folks look at my project, and run `task -a` or `task --sumarize` and it prints a nicely formatted output of what's available.

Right now this is what I get:

![Screen Shot 2022-08-24 at 6 24 16 PM](https://user-images.githubusercontent.com/384279/186534114-78498778-8a14-4de6-a4c6-ea6c2f576512.png)

which is awesome as a starting point, but color makes this more accessible.

For example, look at this tldr page:

![Screen Shot 2022-08-24 at 6 25 04 PM](https://user-images.githubusercontent.com/384279/186534209-e3830076-8762-4231-a87c-2440ff881498.png)

much more accessible for new members of the team looking at a custom set of tools!

Is there any way to accomplish this with task out of the box?

**Comment by andreynering** [comment]
Hi @orenmazor,

This sounds like a reasonable feature request.

We just have to keep in mind that we need to respect `--color=false` or `env NO_COLOR=1` if given, by skipping colors if asked.

**Comment by pd93** [comment]
@andreynering @orenmazor This seemed like low-hanging fruit, so I've done a quick first draft (see the [associated branch](https://github.com/go-task/task/tree/845-colorize-output) and screenshots:

![image](https://user-images.githubusercontent.com/9294862/193102831-d80dc4ef-fa6a-4fd0-9eee-f3dd6febf191.png)

![image](https://user-images.githubusercontent.com/9294862/193102909-6a8c5dde-17c6-4e1c-914d-40c9800a124f.png)

Let me know what you think of the colours - I'm happy to change them. I went with: 
- `green` for tasks as this matches the green when running a task
- `cyan` for descriptions as it complements the green (and the Task logo)
- `yellow` for commands

**Comment by pd93** [comment]
Sidenote, I noticed that `logger.Outf` automatically adds a `\n` to the input string. I'm not a fan of this behaviour as it gives less control to the caller. The new `logger.FOutf` function does not do this to mimic the behaviour of the standard `fmt.Printf` functions and this allows me to use multiple colours on the same line.

I've left the existing `logger.Outf` functionality as-is for now, but I think we should consider changing this in the future.
