### ISSUE TITLE
fish shell support

### ISSUE THREAD

**Issue by andreiborisov** [go-task/task#853]
Is it possible to write commands using a different shell, mainly fish?

**Comment by andreiborisov** [comment]
But how would I specify which shell I want to use? I don't see it the documentation.Just to be clear I meant to write actual commands in `Taskfile.yml`.

**Comment by andreynering** [comment]
Hi @andreiborisov,

That's not supported. Under the hood we use https://github.com/mvdan/sh which supports POSIX, Bash and mksh only (Task uses Bash).

I'll close this as not planned, but I'd still like to know: why would you like to use Fish instead? Bash should be sufficient most of the time.

**Comment by andreiborisov** [comment]
@andreynering the reason is mostly existential😄

Bash scripts proved to be brittle and hard to maintain for us, so we banned their usage in the company altogether. On top of that, young engineers who grew on modern languages are baffled by the arcane old syntax and sensibilities of Bash. Sure, for simple commands there is almost no difference, but in practice, it is easier to not use it at all.
