### ISSUE TITLE
Getting "is a directory" for Task v3.15.0

### ISSUE THREAD

**Issue by m110** [go-task/task#858]
- Task version: v3.15.0
- Operating System: macOS 12.2, Ubuntu

### Example Taskfile showing the issue

```yaml
version: '3'

dotenv:
  - "{{.DOTENV}}"
```

Hey!

We've started getting a weird error message after upgrading to v3.15.0 (v3.14.0 works fine).

```
read /path/to/repository: is a directory
```

It seems the issue is with loading `dotenv` which we use like this:

```yaml
dotenv:
  - "{{.DOTENV}}"
```

I'm not sure if that's a documented feature and if it was working by accident or is an actual bug. We're using this as a way to conditionally load a set of environment variables.

**Comment by pd93** [comment]
@m110 Thanks for the report. I've opened #866 which should address the issue.
