### ISSUE TITLE
File globbing behaving differently from sh/bash/etc. with respect to dot-files

### ISSUE THREAD

**Issue by curio77** [go-task/task#86]
Using globbing patterns such as `build/*` in commands will also include hidden/dot-files (specifically, in my case, an `rm -rf build/*` will also delete `build/.gitkeep`). This is a significant difference to how globbing works in all major (Linux/Un*x) shells. I'm on Linux, using v1.4.4 of `task`.

**Comment by mvdan** [comment]
Agh.

**Comment by mvdan** [comment]
FYI, this should now be fixed in the shell lib.

**Comment by curio77** [comment]
That's great; thanks for fixing this so quickly. :-) I'll give it a try when I get to it.

**Comment by andreynering** [comment]
This should be fixed at master.
