### ISSUE TITLE
/usr/local/bin/task: No such file or directory on Alpine Linux

### ISSUE THREAD

**Issue by 1dal** [go-task/task#87]
Hello, 
i found little problem on Alpine Linux (in my case inside docker:dind v17.09 container).

When i unpacked Task to /usr/local/bin and tried to run it, i ended with this error message:
```
/usr/local/bin/task: No such file or directory
```
Fix/workaround:
```
# see https://stackoverflow.com/a/35613430
mkdir /lib64 && ln -s /lib/libc.musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2
```
Thank you

**Comment by andreynering** [comment]
Hi @1dal 

Thanks for the tip.

By reading that link, seems that compiling with `CGO_ENABLED=0` would also fix it. Am I right? If someone can test it, I could consider adding that flag to the released binaries.

**Comment by andreynering** [comment]
Closing by lack of feedback.

If someone thinks there's an actionable task here to fix something, let me know.
