### ISSUE TITLE
Snapcraft build 1.4.4 fails

### ISSUE THREAD

**Issue by grzegorz-zur** [go-task/task#90]
The latest version 1.4.4 of task is not available in snap package. The snap build failed: https://build.snapcraft.io/user/go-task/snap/108848

**Comment by sascha-andres** [comment]
@andreynering Seems the image used to build is missing curl:

    /tmp/tmpheejg8cc: 14: /tmp/tmpheejg8cc: curl: not found

**Comment by andreynering** [comment]
@grzegorz-zur @sascha-andres Seems that now Snapcraft requires explicitly asking it to install `curl`: https://github.com/go-task/snap/commit/8322f87a24838597715956d3f6bae30cd3a15ecf

It should be fixed now. Thanks for the report! 🙂
