### ISSUE TITLE
Does the doc have Chinese version ?  or how to contribute it?  

### ISSUE THREAD

**Issue by DeronW** [go-task/task#921]
Task is a great tool, does the doc have Chinese version ?  or how to contribute it?

**Comment by andreynering** [comment]
Hi @DeronW! 👋 

We don't have any Chinese person between the maintainers, so we don't have a translation to Chinese. In fact, it's only English for now.

If you are willing to work on it, we have two routes:

1) The easiest one would be to fork this repository and configure GitHub Pages to publish that fork to another one, either a `.github.io` one or another domain if you decide to buy it.
2) [Docusaurus](https://docusaurus.io/), the documentation system we use, [has support to internationalization](https://docusaurus.io/docs/i18n/introduction). In theory I could set that up if we had enough contributors willing to work on the translations.

I just worry that, if the contributors stop translating new text, it would forever be in an incomplete state. Pragmatically speaking, maintaining just English is much easier.

@DeronW Would be just you, or you have more people willing to help?

**Comment by DeronW** [comment]
Well, it's just me, I understand there will be continuous workload to update different language doc, be honestly I could work on the doc few time a year, and last some years. But still I hope to there is a link, inside https://taskfile.dev/ , to the Chinese doc(make it officially is important). So I should prefer way #1 and make pull request with an Chinese doc link.

**Comment by andreynering** [comment]
@DeronW Nice! I would certainly allow a link in the website to the Chinese version 👍

**Comment by DeronW** [comment]
@andreynering The translation is complete, and because GitHub Pages are restricted, so I prefer https://readthedocs.org/ to hold docs. Here are 2 links offered by the documents:

https://task-zh.readthedocs.io/zh_CN/v3.18.0/
https://task-zh.readthedocs.io/zh_CN/latest/

v3.18.0 is the current version, which I think should be added to the document in a proper place.

**Comment by andreynering** [comment]
Hi @DeronW,

Thanks a lot for working on this! ❤️ 

Just added a link in the website on 45ab4dc7180b870df35d078a7cb04966eeb95b0a. Still want to add `| [Chinese in Chinese]` to the end of these links, but didn't want to mistype it. Is `中国人` correct? (taken from Google Translator). Links would be `Chinese | 中国人` then.

I didn't know GitHub Pages was restricted on China. If we ever decide to bring the translation to this repo (using Docusaurus' i18n system) we could _also_ consider a move to https://www.netlify.com/ or somewhere else (if not restricted) to help Chinese devs to access it.

Read The Docs is good as well, though. Thanks!

**Comment by DeronW** [comment]
Thanks, that's very effective. 
“中国人” is correct, [Chinese in Chinese] is also fine.
