### ISSUE TITLE
Update Sprig library to include dict's mergeOverwrite/mustMergeOverwrite

### ISSUE THREAD

**Issue by Northburns** [go-task/task#945]
Sprig function library includes new functions e.g. `mergeOverwrite`/`mustMergeOverwrite`. Maybe updating the Sprig library could be considered. Are there maybe non-obvious blockers for this? Cheers!

**Comment by andreynering** [comment]
Yes, [this comment](https://github.com/go-task/slim-sprig/issues/2#issuecomment-813082908) is a good answer to this request as well. We don't have plans to re-add functions that were removed from being from external dependencies ATM.
