### ISSUE TITLE
Allow for changing the order of tasks when listing tasks

### ISSUE THREAD

**Issue by pioio** [go-task/task#946]
Right now tasks are always listed alphabetically.
For large taskfiles such ordering does not always provide the most logical way of displaying/grouping tasks.

Please implement the ability to list task in the order in which they are defined via new a Taskfile.yaml toplevel setting (e.g. called "order", or some other name to that effect)

---
Discussion: What should be the order of tasks when including other Taskfiles?
Proposed implementation:

When definition-order is used:
(1) the order of included taskfiles should matter
(2) the order of tasks coming from included taskfiles should be the same as when listing those included taskfiles directly

So, for example, given 3 taskfiles:

```
Taskfile.yaml  # the main one, importing the other two
---
order: definition    # we're changing from the default alphanumeric ordering
includes:
  b: ./TaskfileB.yaml
  a: ./TaskfileA.yaml

tasks:
  
  foobar:
     (...)
  bar:
     (...)
```

```
TaskfileB.yaml:
---
order: alphanumeric # the default ordering

tasks:
  task2:
    (...)
  task1:
    (...)
```

```
TaskfileA.yaml
---
# no ordering specified, so use the default
tasks:
  task2:
    (...)
  task1:
    (...)
```

The result of listing tasks in Taskfile.yaml:
```
b:task2   # List "b" tasks first - respect the order of "includes".  List task2 first - respect the "order: definition" inside TaskfileB)
b:task1
a:task1  # within "a", we have alphanumeric ordering (as implicitly defined by defaults in TaskfileA.yaml)
a:task2
foobar  # finally, tasks defined in the main file
bar
```

Optionally, additionally it should also be possible to define the relative placement of tasks define in the main Taskfile.yaml - whether they end up after include tasks, or before them.

**Comment by pd93** [comment]
Seems reasonable to me. However, I think the proposed solution would be more consistent with #806 if the tasks in the root Taskfile were to be listed first.

Also, your proposal suggests a top-level key in the Taskfile. It might be a good idea to have a `--sort` flag (or similar) on the CLI. This would allow scripts that depend on `--list` and `--list-all` to override the sort order defined in the file in case they want to do searching/filtering etc.
