### ISSUE TITLE
[Feature Request] Allow variables from std input 

### ISSUE THREAD

**Issue by sadlil** [go-task/task#95]
Hi, This looks like a good tool to use as build tool. But for some cases it is good to have vars input directly while running, As an example May be like

`task <name> Var1=Ok Var2=NotOk`. That could be a great feature to add.

**Comment by JulienBreux** [comment]
@sadlil you can use the env vars for that?

**Comment by smyrman** [comment]
`task <name> Var1=Ok Var2=NotOk.` Did you try it? At least for task 1.x this used to work -- haven't tried task 2.0 yet.

As for task 1, there is a subtle differnce to be aware of for `task <name> Var1=Ok Var2=NotOk` v.s. `Var1=Ok Var2=NotOk task <name>` in which the latter would also set the variables in the _environment_, making them available to sub-processes...

**Comment by sadlil** [comment]
This works actually, that was my bad. Sorry for that.
Thanks for this awesome lib.
