### ISSUE TITLE
Environment taskfile is running

### ISSUE THREAD

**Issue by wlwwt** [go-task/task#955]
Hi there,

I am using taskfile to automate a lot of my dev project environments. Strange thing is, when i run commands in terminal or via taskfile i get different results. It happens always on commands "changing" the terminal.

An example would be, when I activate virtual environments in python.

Screenshot shows, when it is activated via task, nothing happens (but also no error). Same command directly in terminal activates correctly 

<img width="618" alt="Bildschirmfoto 2022-12-16 um 10 15 58" src="https://user-images.githubusercontent.com/2924324/208065353-900256cc-c3ef-4243-89f0-613b6402f1cc.png">

Any info, if and how this could be solved.

Thanks

**Comment by andreynering** [comment]
Hi @wlwwt,

Unfortunately, the use case you want is not possible to implement.

Commands inside Task runs on its own isolated process, and won't affect your shell.
