### ISSUE TITLE
JSONSchema `interval` incorrect

### ISSUE THREAD

**Issue by delaneyj** [go-task/task#962]
![image](https://user-images.githubusercontent.com/438252/209196370-978406b5-385d-4dc2-8752-af2447d20b9a.png)

In https://taskfile.dev/schema.json interval uses `"$ref": "#/definitions/3/run"` which seems invalid.

**Comment by pd93** [comment]
@delaneyj Well spotted. Looks like a copy/paste error when we migrated and update the schema back into this repo. Fixed in #965.
