### ISSUE TITLE
Unwanted evaluation of string

### ISSUE THREAD

**Issue by ogorzalka** [go-task/task#966]
Hi !

I wanted to execute a task only if a container is not running with this code : 

```
if [ ! "$( docker container inspect -f '{{.State.Status}}' 'traefik' )" == "running" ]; then
          #docker-compose -f docker-compose-traefik.yml up -d
fi
```

The problem is that task interpretate the `{{.State.Status}}` as a variable. Is there a way to indicate to task to not evaluate this string ?

Thanks !

- Task version: 3.0
- Operating System: Ubuntu 22

**Comment by 4x0v7** [comment]
You'll need to escape the brackets with backticks like `{{`{{.VAR}}`}}`

**Comment by ogorzalka** [comment]
Oh thanks, I haven't read this on the docs 🙏
