### ISSUE TITLE
Adding task to stackshare

### ISSUE THREAD

**Issue by GandelXIV** [go-task/task#983]
I have been using Taskfiles a lot and would like to add it to my stack on [stackshare](https://stackshare.io/gandelxiv/drip-v3). However it is not listed in the tools since it has not been added yet.

**Comment by andreynering** [comment]
Hi @GandelXIV,

I suggested it last week and today I noticed that they have added it: https://stackshare.io/task

Thanks for the suggestion.

**Comment by GandelXIV** [comment]
Nice!
