### ISSUE TITLE
Please consider to add new special variable TASK_VERSION

### ISSUE THREAD

**Issue by skaluzka** [go-task/task#990]
I'm using few various task executables in very mixed and inconsistent
environment. Sometimes I miss an equivalent of `MAKE_VERSION` or `BASH_VERSION`
variable.

In bash, there is a `BASH_VERSION` variable available to determine the bash
interpreter version:

    $ bash -c 'echo $BASH_VERSION'
    5.1.16(1)-release
    $ 

In GNU Make, there is also similar variable, called `MAKE_VERSION` (you can
see more details about it in official GNU Make documentation
https://www.gnu.org/software/make/manual/html_node/Quick-Reference.html#Quick-Reference).

Would it be possible to extend the list of task's special variables available
on the templating system? Could you please consider to add a new one called,
for example, a `TASK_VERSION` ??

This could be useful for some debug investigations while running the same
jobs with various task executables.

**Comment by andreynering** [comment]
Hi @skaluzka,

This is a good idea, and should be easy to implement.

If anyone is interested to contribute, these most special vars are defined here:

https://github.com/go-task/task/blob/ecc65a218e6be0c17b2669b20cc0e169ec93fa3f/internal/compiler/v3/compiler_v3.go#L183-L186

We'll to add it to this section of the documentation as well:

https://taskfile.dev/api/#special-variables
