### ISSUE TITLE
unable to install task from install script

### ISSUE THREAD

**Issue by andrewhsu** [go-task/task#994]
When I try to install `task` using the [install script](https://taskfile.dev/installation/#install-script):
```
sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d
```

I get the error:
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9634  100  9634    0     0   125k      0 --:--:-- --:--:-- --:--:--  125k
go-task/task info checking GitHub for latest tag
go-task/task debug http_download https://github.com/go-task/task/releases/latest
go-task/task info found version:  <!DOCTYPE html> <html lang= for  <!DOCTYPE html> <html lang=/linux/amd64
go-task/task debug downloading files into /tmp/tmp.b2uMiIWNs0
go-task/task debug http_download https://github.com/go-task/task/releases/download/ <!DOCTYPE html> <html lang=/task_linux_amd64.tar.gz
```

I believe the install script use to work earlier in the day, so I feel something may have changed recently. It looks like [install-task.sh](https://github.com/go-task/task/blob/master/install-task.sh) hasn't been modified in a while so possibly something on github side?

**Comment by andreynering** [comment]
Hi @andrewhsu, thanks for reporting.

I just tried it and I confirm it is broken.

As you said, the script didn't change for a long time, so yes, I believe it's something on the GitHub end that broke it. 😐

**Comment by mazdakn** [comment]
It seems that it's working again.

**Comment by andreynering** [comment]
Yes, it's working again. I'll close this issue.
